- .github/workflows/rust.yml
Very basic initial CI to run Rust tests.
> beginning CI file

- rust/opendp-ffi/src/core.rs
- rust/opendp-ffi/src/meas.rs
- rust/opendp-ffi/src/trans.rs
- rust/opendp/Cargo.toml
- rust/opendp/src/core.rs
- rust/opendp/src/lib.rs
- rust/opendp/src/meas/mod.rs
- rust/opendp/src/traits.rs
- rust/opendp/src/trans/dataframe.rs
- rust/opendp/src/trans/mod.rs
> error handling

- python/test.py
- rust/opendp-ffi/src/core.rs
- rust/opendp/src/core.rs
> Inconsistent chain constructors

- python/test.py
- rust/opendp-ffi/src/data.rs
- rust/opendp-ffi/src/dispatch.rs
- rust/opendp-ffi/src/trans.rs
- rust/opendp/src/data.rs
- rust/opendp/src/dom.rs
- rust/opendp/src/lib.rs
- rust/opendp/src/trans/dataframe.rs
> trim down the data module, generic dataframe keys

- python/opendp.py
- python/test.py
- rust/opendp-ffi/Cargo.toml
- rust/opendp-ffi/src/core.rs
- rust/opendp-ffi/src/data.rs
- rust/opendp-ffi/src/lib.rs
- rust/opendp-ffi/src/meas.rs
- rust/opendp-ffi/src/trans.rs
- rust/opendp-ffi/src/util.rs
- rust/opendp/Cargo.toml
- rust/opendp/src/core.rs
- rust/opendp/src/data.rs
- rust/opendp/src/dom.rs
- rust/opendp/src/error.rs
- rust/opendp/src/lib.rs
- rust/opendp/src/meas/mod.rs
- rust/opendp/src/traits.rs
- rust/opendp/src/trans/dataframe.rs
- rust/opendp/src/trans/mod.rs
> 32 error handling glue python

- python/test/test_trans.py
- rust/opendp-ffi/src/trans.rs
- rust/opendp/src/trans/mean.rs
- rust/opendp/src/trans/mod.rs
> BoundedMean

- README.md
Closes #91.
* Enhanced README.md, added disclaimers.
> Add disclaimers to README.md

- rust/opendp-ffi/build/main.rs
- rust/opendp-ffi/src/meas/stability.rs
- rust/opendp/src/samplers.rs
closes #100 
- trait CastRug -> CastInternalReal, and implemented for floats
- added a default path to the python src dir for code generation
> Patch Windows build

- python/src/opendp/v1/trans.py
- python/test/test_trans.py
- rust/opendp-ffi/src/trans/bootstrap.json
- rust/opendp-ffi/src/trans/count.rs
- rust/opendp/src/trans/count.rs
This is just a quick constructor for make_count_distinct.
Closes #149.
> add make_count_distinct

- python/src/opendp/v1/trans.py
- python/test/test_trans.py
- rust/opendp-ffi/src/dispatch.rs
- rust/opendp-ffi/src/trans/bootstrap.json
- rust/opendp-ffi/src/trans/cast.rs
- rust/opendp-ffi/src/trans/manipulation.rs
- rust/opendp/src/dom.rs
- rust/opendp/src/traits.rs
- rust/opendp/src/trans/cast.rs
- rust/opendp/src/trans/manipulation.rs
Closes #163
This PR reuses the CheckNull trait to resolve #163 and to add a make_is_null transform.
> Fix "nan" cast; make_is_null transform

- python/example/test.py
- python/src/opendp/v1/mod.py
- python/src/opendp/v1/typing.py
- python/test/test_core.py
- python/test/test_meas.py
- python/test/test_trans.py
- python/test/test_typing.py
- rust/opendp-ffi/src/any.rs
- rust/opendp-ffi/src/dispatch.rs
- rust/opendp-ffi/src/trans/cast.rs
- rust/opendp-ffi/src/trans/clamp.rs
- rust/opendp-ffi/src/trans/manipulation.rs
- rust/opendp-ffi/src/util.rs
- rust/opendp/src/dist.rs
- rust/opendp/src/lib.rs
- rust/opendp/src/poly.rs
- rust/opendp/src/trans/cast.rs
- rust/opendp/src/trans/manipulation.rs
Closes #141
Rename HammingDistance to SubstituteDistance. This should complete renaming for now?
> Rename HammingDistance to SubstituteDistance

- .github/workflows/docs.yml
- .github/workflows/sync-branches.yml
Apparently action expressions only accept single quotes.
> Fixed quoting.

- .github/workflows/sync-branches.yml
Added --force option when pushing updated branch.
> Push with force.

- .github/workflows/release.yml
* Removed --dry-run from cargo call.
> Remaining elements for opendp 0.1 release:

- .github/build_manylinux_binaries.sh
- .github/workflows/release.yml
- .github/workflows/smoke-test.yml
- README.md
- docs/source/resources/dev-guide/general-logistics/dev-environment.rst
- python/README.md
- python/setup.cfg
- python/src/opendp/_lib.py
- python/src/opendp/meas.py
- python/src/opendp/mod.py
- python/test/test_core.py
- python/test/test_meas.py
- python/test/test_typing.py
- rust/opendp-ffi/Cargo.toml
- rust/opendp-ffi/build/main.rs
- rust/opendp-ffi/build/python.rs
- rust/opendp-ffi/src/meas/bootstrap.json
- rust/opendp-ffi/src/meas/mod.rs
- rust/opendp/Cargo.toml
- rust/opendp/src/meas/mod.rs
Closes #220
Closes #217 
Closes #200
> Release 0.1.0

- python/src/opendp/trans.py
- python/test/test_trans.py
- rust/opendp-ffi/src/trans/bootstrap.json
- rust/opendp-ffi/src/trans/mod.rs
- rust/opendp-ffi/src/trans/resize.rs
- rust/opendp/src/samplers.rs
- rust/opendp/src/traits.rs
- rust/opendp/src/trans/mod.rs
- rust/opendp/src/trans/resize.rs
Closes #19 
CheckNull also now has a blanket impl on Option<T: CheckNull>, that checks if the Some is non-null.
> resize transform

- rust/opendp/src/trans/count.rs
> fix output domain on make_count_by_categories

- python/src/opendp/_convert.py
- python/src/opendp/trans.py
- python/src/opendp/typing.py
- python/test/test_convert.py
- python/test/test_meas.py
- python/test/test_trans.py
- rust/opendp-ffi/src/data/mod.rs
- rust/opendp-ffi/src/dispatch.rs
- rust/opendp-ffi/src/lib.rs
- rust/opendp-ffi/src/trans/bootstrap.json
- rust/opendp-ffi/src/trans/dataframe.rs
- rust/opendp-ffi/src/trans/impute.rs
- rust/opendp-ffi/src/trans/manipulation.rs
- rust/opendp-ffi/src/util.rs
Closes #202
Closes #125 
Closes #221
> Vec<String> + HashMap<K, V> data loaders; String args

- python/src/opendp/trans.py
- python/test/test_trans.py
- rust/opendp-ffi/src/any.rs
- rust/opendp-ffi/src/trans/bootstrap.json
- rust/opendp-ffi/src/trans/clamp.rs
- rust/opendp/src/lib.rs
- rust/opendp/src/trans/clamp/mod.rs
> Drop scalar (un)clamp

- docs/source/contact/index.rst
closes #273
Please see discussion at https://github.com/opendp/opendp/issues/273#issuecomment-916375789
> add mailing list, issue tracker, security email #273

- python/src/opendp/accuracy.py
- python/src/opendp/trans.py
- python/test/integration/test_count.py
- python/test/integration/test_sum.py
- python/test/integration/test_variance.py
- python/test/test_trans.py
- rust/opendp-ffi/src/trans/count.rs
- rust/opendp-ffi/src/trans/resize.rs
> integration testing

- docs/source/developer/logistics.rst
- docs/source/user/application-structure.rst
- docs/source/user/combinator-constructors.rst
- docs/source/user/core-structures.rst
- docs/source/user/getting-started.rst
- docs/source/user/measurement-constructors.rst
- docs/source/user/programming-framework.rst
- docs/source/user/supporting-elements.rst
- docs/source/user/transformation-constructors.rst
A fair amount of content was added recently and I finally took the time to swing through and take a look.
This pull request is all for minor stuff:
- typos
- formatting
- grammar
No worries if we don't want all of it.
> minor doc edits and tweaks

- README.md
- docs/source/user/limitations.rst
Closes #301.
* Tweaked README
* Rewrote Limitations
* Fixed Python badge, in case we don't get around to merging #282
> Updates to Limitations section of User Guide

- rust/opendp-ffi/src/trans/count.rs
- rust/opendp/src/meas/stability/mod.rs
- rust/opendp/src/trans/count/mod.rs
> stability histogram relation relaxation

- python/src/opendp/trans.py
- python/test/integration/test_count.py
- python/test/integration/test_histogram.py
- rust/opendp-ffi/src/trans/bootstrap.json
- rust/opendp-ffi/src/trans/count.rs
- rust/opendp/src/trans/count/mod.rs
Closes #377
See the attached issue for context. I'm also open to waiting on the discrete gaussian and looking into constant time granularity adjustments for the geometric mechanism.
> monomorphize floats in integer queries

- docs/source/user/measurement-constructors.rst
- python/src/opendp/meas.py
- python/test/test_meas.py
- rust/opendp-ffi/src/any.rs
- rust/opendp-ffi/src/meas/bootstrap.json
- rust/opendp-ffi/src/meas/gaussian.rs
- rust/opendp/src/accuracy.rs
- rust/opendp/src/meas/gaussian/mod.rs
Closes #403
See the issue for details.
> split analytic gaussian from `make_base_gaussian`

- .github/workflows/release.yml
* Add `tools/` to requirements file paths.
> Fix bogus requirements file paths

- docs/source/user/getting-started.rst
> Document https fallback for clone

- python/src/opendp/meas.py
- python/test/test_meas.py
- rust/src/meas/bootstrap.json
- rust/src/meas/gaussian/analytic.rs
- rust/src/meas/gaussian/ffi.rs
- rust/src/meas/gaussian/mod.rs
> fix infinite loop in `make_base_analytic_gaussian`

- rust/src/meas/alp/mod.rs
- rust/src/traits/arithmetic/mod.rs
- rust/src/traits/cast/mod.rs
> account for extended exponent range in `inf_*` functions

- .github/workflows/release.yml
- .github/workflows/smoke-test.yml
- CHANGELOG.md
- README.md
- VERSION
- docs/source/developer/development-environment.rst
- docs/source/user/getting-started.rst
- python/setup.cfg
- rust/Cargo.toml
- tools/assert_version.py
> preparation for v0.5.0

- tools/assert_version.py
* Fixed Cargo.toml path in assert_version.py
> Fixes for 0.5.0 release

- python/src/opendp/mod.py
- python/src/opendp/transformations.py
- python/test/test_trans.py
- rust/src/combinators/chain/ffi.rs
- rust/src/combinators/postprocess/mod.rs
- rust/src/traits/mod.rs
- rust/src/transformations/b_ary_tree/consistency_postprocessor/ffi.rs
- rust/src/transformations/b_ary_tree/consistency_postprocessor/mod.rs
- rust/src/transformations/b_ary_tree/ffi.rs
- rust/src/transformations/b_ary_tree/mod.rs
- rust/src/transformations/bootstrap.json
- rust/src/transformations/count/ffi.rs
- rust/src/transformations/count/mod.rs
- rust/src/transformations/count_cdf/ffi.rs
- rust/src/transformations/count_cdf/mod.rs
- rust/src/transformations/mod.rs
Resolves #454 
* b-ary tree transformation
* b-ary tree consistency postprocessor
* histogram cdf postprocessor
* histogram quantiles postprocessor
> B-ary trees and CDF postprocessing

- tools/release_tool.py
Closes #537:
* Creates retry command function that will retry any command, and log/report the final failure
* ~~Captures stderr when running command~~
* small name change nit to python version formatting
> Add Retries For Pulling Pypi Repo

- python/src/opendp/_convert.py
- python/test/test_convert.py
> add checks for int ctypes

- python/src/opendp/measurements.py
- python/test/integration/test_sum_int.py
- python/test/test_meas.py
- rust/src/accuracy/mod.rs
- rust/src/measurements/discrete_gaussian/ffi.rs
- rust/src/measurements/discrete_gaussian/mod.rs
Closes #564 
This makes it possible to chain integer sums with the discrete gaussian measurement.
> add `QI` generic to `make_base_discrete_gaussian`

- python/test/test_comb.py
- rust/src/combinators/compose/ffi.rs
- rust/src/combinators/compose/mod.rs
- rust/src/ffi/util.rs
> fix approximate composition FFI

- docs/source/developer/development-environment.rst
- docs/source/examples/pums-data-analysis.ipynb
- docs/source/user/constructors/combinators.rst
- python/src/opendp/combinators.py
- python/test/test_comb.py
- rust/Cargo.toml
- rust/src/combinators/amplify/ffi.rs
- rust/src/combinators/mod.rs
> honest-but-curious feature flag

- docs/source/user/constructors/combinators.rst
- python/src/opendp/combinators.py
- python/src/opendp/transformations.py
- python/test/test_comb.py
- rust/src/combinators/fix_delta/mod.rs
- rust/src/combinators/measure_cast/mod.rs
- rust/src/combinators/measure_cast/pureDP_to_fixed_approxDP/ffi.rs
- rust/src/combinators/measure_cast/pureDP_to_fixed_approxDP/mod.rs
- rust/src/combinators/measure_cast/zCDP_to_approxDP/mod.rs
> `make_pureDP_to_fixed_approxDP` constructor

- .github/workflows/docs.yml
- docs/source/user/constructors/combinators.rst
- python/src/opendp/combinators.py
- python/test/test_comb.py
- rust/src/combinators/measure_cast/mod.rs
- rust/src/combinators/measure_cast/pureDP_to_zCDP/ffi.rs
- rust/src/combinators/measure_cast/pureDP_to_zCDP/mod.rs
> `make_pureDP_to_zCDP` constructor

- .github/workflows/docs.yml
- python/src/opendp/accuracy.py
- rust/src/accuracy/accuracy_to_discrete_gaussian_scale.tex
- rust/src/accuracy/accuracy_to_discrete_laplacian_scale.tex
- rust/src/accuracy/discrete_gaussian_scale_to_accuracy.tex
- rust/src/accuracy/discrete_laplacian_scale_to_accuracy.tex
- rust/src/accuracy/ffi.rs
- rust/src/accuracy/mod.rs
Closes https://github.com/opendp/opendp/issues/577
> discrete accuracy utilities

- docs/Makefile
- python/src/opendp/accuracy.py
- python/src/opendp/transformations.py
- rust/opendp_tooling/src/proven/filesystem.rs
> fix proof paths

- tools/build_tool.py
> Update build_tool.py linux image

- .github/workflows/release.yml
- tools/requirements-publish_tool.txt
> Further changes for linux image

- rust/src/accuracy/mod.rs
> fix accuracy edge cases

- .github/workflows/latex.yml
- rust/src/traits/samplers/cks20/mod.bib
- rust/src/traits/samplers/cks20/mod.rs
- rust/src/traits/samplers/cks20/sample_bernoulli_exp.tex
- rust/src/traits/samplers/cks20/sample_bernoulli_exp1.tex
- rust/src/traits/samplers/cks20/sample_discrete_gaussian.tex
- rust/src/traits/samplers/cks20/sample_discrete_laplace.tex
- rust/src/traits/samplers/cks20/sample_geometric_exp_fast.tex
- rust/src/traits/samplers/cks20/sample_geometric_exp_slow.tex
Dependency for #191.
Dependency for #503.
> proofs for cks20 samplers

- CHANGELOG.md
> 0.6.2 preparation

- tools/publish_tool.py
- tools/rust_build.sh
Fixes #631.
* Add sleep so rustup can settle on windows
* Remove explicit cargo path on windows
* Remove cargo login
> Add sleep so rustup can settle on windows

- docs/source/conf.py
- python/src/opendp/_data.py
- python/src/opendp/extrinsics/_proven.py
- rust/Cargo.toml
- rust/opendp_tooling/src/bootstrap/docstring.rs
- rust/opendp_tooling/src/proven/filesystem.rs
- rust/src/data/ffi.rs
> python extrinsics module

- python/src/opendp/domains.py
- python/src/opendp/measures.py
- python/src/opendp/metrics.py
- python/src/opendp/mod.py
- rust/src/domains/ffi.rs
- rust/src/measures/ffi.rs
- rust/src/metrics/ffi.rs
> free supporting elements

- docs/source/examples/attacks/reconstruction.ipynb
- docs/source/examples/pums-data-analysis.ipynb
- docs/source/user/combinators.rst
- docs/source/user/measurements/additive-noise-mechanisms.ipynb
- docs/source/user/utilities/accuracy/index.rst
- docs/source/user/utilities/parameter-search.rst
- python/src/opendp/measurements.py
- python/src/opendp/mod.py
- python/test/integration/test_count.py
- python/test/integration/test_histogram.py
- python/test/integration/test_sum.py
- python/test/test_comb.py
- python/test/test_meas.py
- rust/src/accuracy/mod.rs
- rust/src/measurements/gaussian/ffi.rs
- rust/src/measurements/gaussian/mod.rs
> dom/met signature: `make_base_gaussian`

- rust/src/ffi/dispatch.rs
- rust/src/measurements/gaussian/ffi.rs
- rust/src/measurements/laplace/ffi.rs
- rust/src/measurements/mod.rs
- rust/src/metrics/mod.rs
> fix release builds

- python/src/opendp/metrics.py
- python/src/opendp/transformations.py
- python/test/test_trans.py
- rust/opendp_tooling/src/bootstrap/partial.rs
- rust/src/metrics/ffi.rs
- rust/src/metrics/mod.rs
- rust/src/transformations/quantile_score_candidates/ffi.rs
- rust/src/transformations/quantile_score_candidates/mod.rs
Closes #751
* FFI for both `make_quantile_score_candidates` and `linf_diff_distance`
> add `make_quantile_score_candidates` ffi

- python/src/opendp/transformations.py
- rust/src/transformations/quantile_score_candidates/compute_score.tex
- rust/src/transformations/quantile_score_candidates/make_quantile_score_candidates.tex
- rust/src/transformations/quantile_score_candidates/pseudocode/compute_score.py
- rust/src/transformations/quantile_score_candidates/pseudocode/make_quantile_score_candidates.py
- rust/src/transformations/quantile_score_candidates/references.bib
> `make_quantile_score_candidates` proof

- python/src/opendp/measurements.py
- python/test/integration/test_quantile.py
- python/test/test_meas.py
- rust/src/lib.sty
- rust/src/measurements/discrete_exponential/ffi.rs
- rust/src/measurements/discrete_exponential/mod.rs
> add `make_base_discrete_exponential` ffi

- python/src/opendp/measures.py
- python/src/opendp/metrics.py
- python/test/test_core.py
- rust/src/measures/ffi.rs
- rust/src/metrics/ffi.rs
> add `UserDistance` and `UserDivergence`

- docs/source/contributor/development-environment.rst
> In venv example, use conventional gitignored name

- SECURITY.md
> Copy SECURITY.md from smartnoise-sdk

- docs/source/index.rst
- Builds on #1055
- Fix #998 
- Fix #982
(Issues shouldn't be closed until this is merged to main.)
> new docs homepage

- docs/source/conf.py
- docs/source/user/transformations.rst
- Fix #1068
- Extended by #1073... but that got too big, and I wanted a simple PR with just the basics.
> Only enable Spinx nitpicks

- docs/Makefile
- docs/README.md
- docs/linkchecker.cfg
Update instructions for PDF build. This works for me... but I'm not great with LaTeX so this may not be the best approach... and maybe there was something wrong in my environment and it should work even without this PR.
(Actually fixing the links to PDFs #1070 turns out to be trickier, because the links are absolute.)
> Update README and Makefile to enable PDF build

- .github/workflows/prepare.yml
- .github/workflows/publish.yml
- .github/workflows/sanity-test.yml
- docs/linkchecker.cfg
- tools/build_tool.py
- tools/channel_tool.py
- tools/publish_tool.py
> Remove negative CLI flags

- .github/workflows/prepare.yml
- .github/workflows/release.yml
Original PR didn't make it all the way to main:
- #1109
> Define a dry_run variable that incorporates fake

- .github/workflows/prepare.yml
- .github/workflows/publish.yml
- .github/workflows/sanity-test.yml
- docs/linkchecker.cfg
- tools/build_tool.py
- tools/channel_tool.py
- tools/publish_tool.py
Original PR didn't make it all the way to main:
- #1106
> Use longer param names for flags

- docs/source/user/measurements.rst
- python/src/opendp/mod.py
- python/src/opendp/typing.py
Small change: makes the doctests a little more idiomatic, but it's subjective.
> More idiomatic doctests

- .flake8
- python/src/opendp/_convert.py
- python/src/opendp/_lib.py
- python/src/opendp/context.py
- python/src/opendp/mod.py
- python/src/opendp/typing.py
- python/test/context/test_context.py
- python/test/test_binary_search.py
- python/test/test_convert.py
- python/test/test_core.py
- python/test/test_decorators.py
This is primarily about gaining familiarity with the codebase. I've skipped sections where the correct behavior wasn't clear -- I don't want to add tests that blindly assert the current behavior, without understanding whether that behavior is correct or not.
> Improve test coverage

- docs/Makefile
> Remove vestigial lines in Makefile

- rust/Cargo.toml
> update rug dependency

- docs/requirements.in
- docs/requirements.txt
- python/src/opendp/mod.py
- rust/Cargo.toml
Just get doc-IN-PROGRESS to a passing state. 
- Fix rust dependency problem
- Fix missing sphinx-tabs dependency
- Fix links
> Fix docs in progress

- .github/workflows/smoke-test.yml
- python/setup.cfg
- python/src/opendp/_data.py
- python/src/opendp/_lib.py
- python/test/extrinsics/test_csprng.py
- rust/opendp_tooling/src/codegen/python_typemap.json
- rust/src/data/ffi.rs
- tools/publish_tool.py
Closes #1164
I'm sourcing noise from our Rust CSPRNG, for consistency.
> implement csprng for numpy

- rust/src/traits/samplers/cks20/sample_discrete_laplace.tex
> fix typo in discrete Laplace density proof

- python/src/opendp/core.py
- python/src/opendp/domains.py
- python/src/opendp/measurements.py
- python/src/opendp/metrics.py
- python/src/opendp/transformations.py
- rust/opendp_tooling/src/codegen/python.rs
> selectively apply Optional hints in generated Python

- .github/workflows/release.yml
> explain fromJSON

- R/opendp/DESCRIPTION
- tools/assert_version.py
- tools/channel_tool.py
Closes #1198
Usage of the `debmutate` Python package seems to have changed, this fixes reads/writes of the R DESCRIPTION file.
> fix debmutate usage

- docs/source/user/utilities/parameter-search.rst
- Fix #1201
Mike noted on slack:
> It's ever-so-slightly tighter, which means the overall guarantees have gotten a little bit looser
> you have to have slightly narrower clipping bounds now for the same level of privacy
> One character fix to doctest

- docs/Makefile
- docs/source/conf.py
- Fix #1160 (though, at the end of that comment thread I don't have the sense that we're 100% confident about this.)
> Remove Rust doc TODO

- .github/workflows/weekly-doc-check.yml
- docs/Makefile
- rust/opendp_derive/src/lib.rs
- rust/src/measurements/alp/mod.rs
- rust/src/metrics/mod.rs
- rust/src/traits/samplers/cks20/mod.rs
- rust/src/traits/samplers/discretize/mod.rs
- Fix #1152 
... except with the make build I don't get the same error in `opendp_derive`. Draft until I understand the difference.
> Fix rust build doc warnings

- CHANGELOG.md
> 0.9.0 release prep

- .github/workflows/docs.yml
> fix R docs download path in CI

- .flake8
- tools/build_tool.py
- tools/utils.py
> Use isinstance where appropriate

- rust/src/domains/mod.rs
- Fix #1225
Did a build from scratch with this change and there are no warnings.
> remove reference to poly

- .github/workflows/publish.yml
- Fix #1234
If you already have something in the works, just close this.
> reverse ternary, so it is not confused by false-y empty string

- docs/source/contributor/development-environment.rst
> Explain relationship between `bindings` and `derive`

- .flake8
- .github/workflows/smoke-test.yml
- docs/source/conf.py
- python/requirements-dev.in
- python/requirements-dev.txt
- python/src/opendp/_convert.py
- python/src/opendp/_extrinsics/__init__.py
- python/src/opendp/_extrinsics/domains/__init__.py
- python/src/opendp/_extrinsics/sklearn/__init__.py
- python/src/opendp/_lib.py
- python/src/opendp/mod.py
- python/src/opendp/typing.py
- python/test/integration/test_count.py
- python/test/integration/test_mean.py
- Fix #1260 -- Comments on separate lines!
- Fix #1069 -- Fix the ones that need fixing, and explain the rest.
- Add a couple TODOs -- Will file follow-up issues if you're in agreement.
If you would prefer to have stricter linting and fewer ignores, that could work... though if we get really strict we should probably use black and/or pre-commit-hooks.
Conversely, if you think something I've marked as a TODO wouldn't be helpful, that's welcome feedback too.
> Fix the flake8 warnings that really need it

- tools/r_stage.sh
> do not generate NEWS.md

- .gitignore
I noticed no PR was made from this branch. I hope you don't mind I made one @abigail-gentle!
> LaTeX cache, temp, and output files

- .github/workflows/smoke-test.yml
> Fix erratic R linting errors, hopefully

- .github/workflows/build.yml
- .github/workflows/credential-check.yml
- .github/workflows/publish.yml
> 3.8 -> 3.12 in CI (except for smoke-test)

- .github/workflows/README.md
- .github/workflows/weekly-doc-check.yml
- R/opendp/README.md
- README.md
- docs/cla/README.md
- Fix #1428
- Update the badges on the README, so we'll be nudged to fix problems sooner.
----------
Running workflow to see if this fixes anything: https://github.com/opendp/opendp/actions/runs/8425284607
Install works! now just want to fix the links...
Running again with changes: https://github.com/opendp/opendp/actions/runs/8426112741
huh: still fails. Maybe warnings and not just errors cause non-zero status?
```
That's it. 66 links in 69 URLs checked. 16 warnings found. 0 errors found.
Stopped checking at 2024-03-25 19:53:16+000 (7 seconds)
Error: Process completed with exit code 123.
```
> Fix weekly-doc-check

- rust/build/derive.rs
> For generate_header def and use, ffi -> bindings

- docs/source/api/user-guide/combinators/index.rst
- docs/source/api/user-guide/measurements/index.rst
- docs/source/api/user-guide/programming-framework/supporting-elements.rst
- docs/source/api/user-guide/transformations/index.rst
- docs/source/api/user-guide/utilities/accuracy.rst
- docs/source/api/user-guide/utilities/parameter-search.rst
- docs/source/api/user-guide/utilities/typing.rst
- docs/source/conf.py
- docs/source/getting-started/installation-TODO.rst
- docs/source/getting-started/quickstart-TODO.rst
- python/src/opendp/prelude.py
- Fix #1284
- and remove some other unused sphinx options while I'm here.
> Remove sphinx doctest tags

- docs/source/contributing/development-environment.rst
- docs/source/index.rst
> Explain extra installs for R / Add "is" on homepage

- docs/source/theory/dp-with-opendp.ipynb
> Update introductory paragraph, remove last outdated section

- python/.pytest.ini
- python/src/opendp/context.py
- python/test/context/test_context.py
- Fix #1451
- Make xfail strict
> fix split_by_weights

- python/src/opendp/context.py
- python/test/context/test_context.py
> Warn if large priv loss

- docs/source/conf.py
- I believe it was broken by changes in #1450
- Bring back all the extensions that that commit removed.
- Towards #1463
> fix nightly docs build

- R/opendp/R/typing.R
> delete duplicate def of parse_or_infer

- .github/workflows/smoke-test.yml
- docs/source/.Rprofile
- docs/source/.lintr
- docs/source/getting-started/code/typical-workflow-framework.R
- docs/source/getting-started/code/typical-workflow-framework.rst
- docs/source/getting-started/typical-workflow.rst
- tools/r_doc_examples.py
- fix #1460
- fix #1287
Draft for now.
> Add R example to "typical workflow"

- .github/workflows/build.yml
- .github/workflows/smoke-test.yml
- python/src/opendp/_extrinsics/_make_np_eigenvector/__init__.py
- rust/Cargo.toml
- rust/src/combinators/mod.rs
- rust/src/domains/mod.rs
- rust/src/domains/polars/mod.rs
- rust/src/domains/polars/series/mod.rs
- rust/src/error.rs
- rust/src/traits/mod.rs
- rust/src/transformations/mean/mod.rs
- rust/src/transformations/sum_of_squared_deviations/mod.rs
- rust/src/transformations/variance/mod.rs
> Polars: add `SeriesDomain`

- rust/src/domains/polars/frame/mod.rs
- rust/src/domains/polars/mod.rs
> Polars: add `FrameDomain`

- .github/workflows/build.yml
- .github/workflows/smoke-test.yml
- R/opendp/src/opendp.h
- python/setup.cfg
- python/src/opendp/_convert.py
- python/src/opendp/_data.py
- python/src/opendp/domains.py
- python/src/opendp/typing.py
- python/test/conftest.py
- python/test/test_polars.py
- rust/Cargo.toml
- rust/opendp_tooling/src/bootstrap/arguments.rs
- rust/opendp_tooling/src/bootstrap/mod.rs
- rust/opendp_tooling/src/bootstrap/signature.rs
- rust/opendp_tooling/src/codegen/python.rs
- rust/opendp_tooling/src/codegen/r/c.rs
- rust/opendp_tooling/src/codegen/r/mod.rs
- rust/opendp_tooling/src/codegen/r/r.rs
- rust/opendp_tooling/src/lib.rs
- rust/src/data/ffi.rs
- rust/src/domains/polars/series/ffi.rs
- rust/src/domains/polars/series/mod.rs
- rust/src/ffi/util.rs
- tools/update_notes.R
> Polars: `series_domain` ffi

- R/opendp/R/metrics.R
- R/opendp/src/Ropendp.h
- R/opendp/src/lib.c
- R/opendp/src/metrics.c
- R/opendp/src/opendp.h
- python/src/opendp/_convert.py
- python/src/opendp/metrics.py
- python/test/test_metrics.py
- rust/src/data/ffi.rs
- rust/src/ffi/util.rs
- rust/src/metrics/ffi.rs
- rust/src/metrics/mod.rs
> partition distance

- R/opendp/src/opendp.h
- python/src/opendp/_convert.py
- python/src/opendp/domains.py
- python/src/opendp/typing.py
- python/test/test_convert.py
- python/test/test_polars.py
- rust/opendp_tooling/src/bootstrap/signature.rs
- rust/opendp_tooling/src/codegen/r/mod.rs
- rust/src/data/ffi.rs
- rust/src/domains/polars/expr/ffi.rs
- rust/src/domains/polars/expr/mod.rs
- rust/src/domains/polars/frame/mod.rs
- rust/src/domains/polars/mod.rs
- rust/src/ffi/util.rs
> Polars: add `ExprDomain`

- docs/Makefile
- docs/source/conf.py
- Fix #1477 
Pulling this out to a standalone script that they both reference seems like overkill, but this doesn't seem great either.
> Just add a note to explain duplication

- python/src/opendp/mod.py
- python/src/opendp/typing.py
> Minor typing edit: float implies int

- python/test/test_interactive.py
- rust/opendp_tooling/src/codegen/r/mod.rs
- Fix #1527
Should be sufficient.
> udf -> plugin

- python/src/opendp/context.py
- Fix #1411
- Replace #1424: It got too complicated
> fix return signature on loss_of

- python/src/opendp/measurements.py
- rust/src/measurements/code/make_gaussian.rst
- rust/src/measurements/code/make_geometric.rst
- rust/src/measurements/code/make_laplace.rst
- rust/src/measurements/code/make_report_noisy_max_gumbel.rst
- rust/src/measurements/code/then_gaussian.rst
- rust/src/measurements/code/then_geometric.rst
- rust/src/measurements/code/then_laplace.rst
- rust/src/measurements/code/then_report_noisy_max_gumbel.rst
- Fix #1570
- I'll file a separate PR that extends this by using the same snippet for both "then" and "make" docs: I'm not sure that either of us are sure about the best course.
> Merge "then" examples into "make" and regenerate

- .github/workflows/smoke-test.yml
- Fix #1617
(Took me too long to realize that upload artifact does not consider the directory for the job.)
> Confirm python coverage ran

- docs/source/api/user-guide/programming-framework/core-structures.rst
- docs/source/api/user-guide/programming-framework/index.rst
- docs/source/api/user-guide/programming-framework/supporting-elements.rst
Just re-reading the User Guide and making some edits along the way. I'll start a new PR for the next batch. Comments give some motivation, but this is all subjective, and I don't feel too strongly about any of it.
> Misc. copy-edits on the API User Guide

- python/src/opendp/mod.py
- python/test/test_trans.py
- Remove `pragma: no cover` where it already is covered.
- Add more tests.
- Filed #1650
> Improve test coverage in `mod.py`

- python/src/opendp/_lib.py
- Towards #1035 
- add a couple lines of doc tests
- Remove ignores that do not seem to be needed
- add notes in a couple places where we have branches that are not exercised... before just adding a test to exercise them, are we sure we need this behavior?
> Improved test coverage in _lib.py

- docs/source/index.rst
Text changes for who is using section
> update for "who's using OpenDP" section  #1593

- python/src/opendp/_lib.py
- python/test/test_polars.py
- rust/src/core/polars/mod.rs
- rust/src/measurements/make_private_expr/expr_index_candidates/mod.rs
- rust/src/measurements/make_private_expr/expr_index_candidates/test.rs
- rust/src/measurements/make_private_expr/expr_report_noisy_max_gumbel/mod.rs
- rust/src/measurements/make_private_expr/expr_report_noisy_max_gumbel/test.rs
- rust/src/measurements/make_private_expr/mod.rs
- rust/src/transformations/make_stable_expr/expr_discrete_quantile_score/mod.rs
- rust/src/transformations/make_stable_expr/expr_discrete_quantile_score/plugin_dq_score.rs
Closes #1497
The output of the RNM Gumbel mechanism is the index of the selected candidate, not the selected candidate. This PR adds a postprocessing function that returns the candidate at each selected index.
> Polars: quantile postprocessing

- rust/src/transformations/make_stable_expr/expr_boolean_function/mod.rs
- rust/src/transformations/make_stable_expr/expr_boolean_function/test.rs
- rust/src/transformations/make_stable_expr/mod.rs
Adds support for the following transformations:
* is_null
* is_not_null
* is_finite
* is_infinite
* is_nan
* is_not_nan
* not
> Polars: boolean functions

- rust/src/transformations/make_stable_expr/expr_len/mod.rs
- rust/src/transformations/make_stable_expr/expr_len/test.rs
- rust/src/transformations/make_stable_expr/expr_sum/test.rs
- rust/src/transformations/make_stable_expr/mod.rs
> Polars: length transformation

- rust/src/core/polars/mod.rs
- rust/src/domains/polars/frame/mod.rs
- rust/src/measurements/make_private_expr/mod.rs
- rust/src/measurements/make_private_lazyframe/mod.rs
- rust/src/measurements/make_private_lazyframe/select/mod.rs
- rust/src/measurements/make_private_lazyframe/select/test.rs
- rust/src/transformations/make_stable_expr/mod.rs
- rust/src/transformations/make_stable_lazyframe/mod.rs
> Polars: select measurement

- rust/src/domains/polars/frame/mod.rs
- rust/src/transformations/make_stable_lazyframe/h_stack/mod.rs
- rust/src/transformations/make_stable_lazyframe/h_stack/test.rs
- rust/src/transformations/make_stable_lazyframe/mod.rs
GitHub got confused and closed #1592, so I did a manual patch job. Please continue this review from 6/13!
> Polars: add horizontal stack

- docs/requirements_notebooks.txt
- python/setup.cfg
> bound numpy version to 1.x

- docs/source/index.rst
> Replace youtube link with Swiss FSO blog

- docs/source/getting-started/examples/pums-data-analysis.ipynb
> Fix links in pums-data-analysis

- python/src/opendp/_extrinsics/_utilities.py
> `with_privacy` should pass `args` and `kwargs`

- python/test/test_supporting_elements.py
- rust/src/domains/ffi.rs
> chore: add release dtypes to ffi for AtomDomain and OptionDomain

- docs/source/contributing/development-environment.rst
> Add a little more explanation for honest-but-curious

- docs/source/api/user-guide/index.rst
- docs/source/contributing/development-environment.rst
> docs: features and env vars

- R/opendp/src/convert_elements.c
Closes #1340
I can't conclusively verify that the problem is closed, but if we encounter the issue again in CI, then we'll re-open.
> R: fix null pointer error

- python/src/opendp/polars.py
- python/test/test_polars.py
> Polars: emulate Polars APIs for type annotations

- python/src/opendp/mod.py
- python/test/test_core.py
> python: don't allow iteration over base classes

- rust/src/data/ffi/mod.rs
- rust/src/transformations/make_stable_expr/expr_sum/mod.rs
- rust/src/transformations/sum/float/checked/mod.rs
- rust/src/transformations/sum/int/checked/mod.rs
> Polars: nit error messages

- python/test/test_polars.py
- rust/src/domains/polars/frame/mod.rs
- rust/src/measurements/make_private_expr/expr_noise/mod.rs
- rust/src/measurements/make_private_expr/expr_report_noisy_max/mod.rs
- rust/src/measurements/make_private_expr/mod.rs
> Polars: evenly allocate budget amongst queries, by default

- R/opendp/src/opendp.h
- python/src/opendp/polars.py
- python/test/test_polars.py
- rust/src/data/ffi/polars.rs
- rust/src/measurements/code/make_private_lazyframe.rst
- rust/src/measurements/make_private_expr/expr_literal/test.rs
- rust/src/polars/mod.rs
> Polars: shuffle OnceFrame output

- python/test/test_polars.py
- rust/src/polars/mod.rs
> Polars: test pickle bombs

- docs/requirements_notebooks.txt
I think this is the change we need for the Polars notebooks. I started applying it piece meal, but makes more sense to get approval and then merge the updates in `main` to the branches
> dependencies for polars notebooks

- .github/workflows/README.md
> docs: release process

- .github/workflows/smoke-test.yml
- docs/source/contributing/development-environment.rst
- python/test/test_polars.py
- rust/src/polars/mod.rs
> Polars: OPENDP_LIB_PATH -> OPENDP_POLARS_LIB_PATH

- docs/source/getting-started/statistical-modeling/regression.ipynb
> Fix dp.np_array2_domain -> dp.numpy.array2_domain

- docs/source/getting-started/code/quickstart-context.rst
- docs/source/getting-started/quickstart.rst
- docs/source/getting-started/typical-workflow.rst
- Preparing for #1780
It seemed that the discussion of the API layers needed one more layer, and that it might fit better on the previous page.
> docs: document API layers

- .binder/requirements.txt
- docs/linkchecker-external.cfg
- docs/linkchecker.cfg
- docs/source/conf.py
- tools/assert_version.py
- tools/channel_tool.py
- Fix #1873
- also, fix #903, or at least render it moot
- close #955, by dropping binder
If it turns out we _don't_ want to do this, that would also be a good thing to learn.
> remove references to binder

- docs/source/getting-started/assessing-utility/noise.ipynb
- docs/source/getting-started/tabular-data/keys.ipynb
I changed the default branch for consistency while working on https://github.com/opendp/dp-test-datasets/pull/1 ... but I should have kept the old one around and made these fixes first.
> Change `master` to `main` in two notebooks

- rust/src/accuracy/polars/mod.rs
- rust/src/accuracy/polars/test.rs
> Polars: support means in accuracy utility

- rust/src/accuracy/mod.rs
- rust/src/error/mod.rs
- rust/src/measurements/make_private_lazyframe/group_by/mod.rs
- rust/src/polars/mod.rs
- rust/src/transformations/dataframe/apply/mod.rs
- rust/src/transformations/dataframe/subset/mod.rs
> fix: fill in Rust error message templates

- README.md
- Will consider this to close #371.
The README here can be a template for any other repos, and if there are other suggestions, we should just make them here.
> Add logo on README

- docs/source/contributing/development-environment.rst
> Add documentation for python vs r cargo build

- .gitignore
- docs/source/getting-started/tabular-data/group-by.ipynb
> fix: infinite loop in data download

- python/src/opendp/mod.py
- Fix #1850
Rendered docs locally, and it looks good.
> Add pointer to list of features from API docs

- rust/src/data/ffi/mod.rs
- rust/src/domains/ffi.rs
- rust/src/domains/polars/frame/ffi.rs
- rust/src/measurements/gaussian/ffi.rs
- rust/src/measurements/gumbel_max/ffi.rs
- rust/src/measurements/laplace/ffi.rs
- rust/src/measurements/make_private_expr/ffi.rs
- rust/src/measurements/make_private_lazyframe/ffi.rs
- rust/src/transformations/cast/ffi.rs
- rust/src/transformations/cast_metric/ffi.rs
- rust/src/transformations/clamp/ffi.rs
- rust/src/transformations/impute/ffi.rs
- rust/src/transformations/manipulation/ffi.rs
- rust/src/transformations/resize/ffi.rs
> fix: nightly docs.rs build fails on shadowed generics

- R/opendp/src/opendp.h
- docs/source/getting-started/tabular-data/group-by.ipynb
- python/src/opendp/extras/polars/__init__.py
- python/test/test_polars.py
- rust/opendp_tooling/src/codegen/r/mod.rs
- rust/src/accuracy/code/summarize_polars_measurement.rst
- rust/src/accuracy/polars/ffi.rs
- rust/src/accuracy/polars/mod.rs
- rust/src/accuracy/polars/test.rs
> Polars: rename accuracy to summarize

- python/src/opendp/mod.py
- python/test/test_binary_search.py
> usability: don't mask predicate error in binary search

- rust/Cargo.toml
> docs: include Polars in docs.rs build

- CODE_OF_CONDUCT.md
> add "mailto" and "https" in code of conduct

- .github/workflows/smoke-test.yml
- docs/source/api/user-guide/programming-framework/index.rst
- docs/source/contributing/proof-initiation.rst
- docs/source/getting-started/examples/pums-data-analysis.ipynb
- Fix #1046
- And add a CI check to make sure we don't introduce any new ones.
> Add check for absolute links to docs.opendp.org

- docs/source/index.rst
> Update pysyft info

- .github/workflows/README.md
- CODE_OF_CONDUCT.md
- Fix #2012
Got approval from Sharon on Slack.
> Fix links for Title IX and Maintainer Notes

- R/opendp/R/mod.R
- R/opendp/src/convert.c
- R/opendp/src/convert_elements.c
- R/opendp/src/convert_elements.h
- R/opendp/src/opendp.h
- R/opendp/tests/testthat/test-measurements.R
- docs/source/api/user-guide/combinators/index.rst
- docs/source/getting-started/examples/pums-data-analysis.ipynb
- python/src/opendp/_convert.py
- python/src/opendp/mod.py
- python/test/test_comb.py
- python/test/test_meas.py
- rust/src/combinators/fix_delta/ffi.rs
- rust/src/combinators/fix_delta/mod.rs
- rust/src/combinators/measure_cast/zCDP_to_approxDP/mod.rs
- rust/src/data/ffi/mod.rs
- rust/src/ffi/util.rs
- rust/src/measures/mod.rs
> rename SMDCurve to PrivacyProfile

- python/test/test_polars.py
- rust/src/transformations/make_stable_expr/expr_cast/mod.rs
- rust/src/transformations/make_stable_expr/expr_cast/test.rs
- rust/src/transformations/make_stable_expr/mod.rs
> Polars: add cast transformation

- R/opendp/R/mod.R
- docs/source/api/user-guide/combinators/index.rst
- python/src/opendp/_convert.py
- python/src/opendp/context.py
- python/src/opendp/extras/polars/__init__.py
- python/test/context/test_context.py
- python/test/test_comb.py
- python/test/test_polars.py
- rust/src/combinators/fix_delta/ffi.rs
- rust/src/combinators/fix_delta/mod.rs
- rust/src/combinators/fix_delta/test.rs
- rust/src/combinators/measure_cast/approximate/ffi.rs
- rust/src/combinators/measure_cast/zCDP_to_approxDP/ffi.rs
- rust/src/combinators/measure_cast/zCDP_to_approxDP/mod.rs
- rust/src/combinators/measure_cast/zCDP_to_approxDP/test.rs
- rust/src/combinators/sequential_compositor/noninteractive/ffi.rs
- rust/src/combinators/sequential_compositor/noninteractive/mod.rs
- rust/src/data/ffi/mod.rs
- rust/src/ffi/util.rs
- rust/src/metrics/mod.rs
> add approximate zCDP

- R/opendp/src/opendp.h
- python/src/opendp/extras/polars/__init__.py
- python/test/test_polars.py
- rust/opendp_tooling/src/codegen/r/mod.rs
- rust/src/domains/ffi.rs
- rust/src/domains/mod.rs
- rust/src/domains/polars/series/ffi.rs
- rust/src/domains/polars/series/mod.rs
- rust/src/ffi/util.rs
- rust/src/transformations/make_stable_expr/expr_cut/mod.rs
- rust/src/transformations/make_stable_expr/expr_cut/test.rs
- rust/src/transformations/make_stable_expr/expr_fill_null/mod.rs
- rust/src/transformations/make_stable_expr/mod.rs
> Polars: add cut transformation and categorical dtype

- R/opendp/src/opendp.h
- python/test/test_polars.py
- rust/opendp_tooling/src/codegen/r/mod.rs
- rust/src/accuracy/mod.rs
- rust/src/accuracy/tail_bounds/conservative_continuous_gaussian_tail_to_alpha.tex
- rust/src/accuracy/tail_bounds/conservative_discrete_laplacian_tail_to_alpha.tex
- rust/src/accuracy/tail_bounds/erfc_err_analysis.py
- rust/src/accuracy/tail_bounds/mod.rs
- rust/src/accuracy/tail_bounds/test.rs
- rust/src/accuracy/test.rs
- rust/src/combinators/fix_delta/test.rs
- rust/src/data/ffi/mod.rs
- rust/src/measurements/make_private_expr/mod.rs
- rust/src/measurements/make_private_lazyframe/ffi.rs
- rust/src/measurements/make_private_lazyframe/group_by/mod.rs
- rust/src/measurements/make_private_lazyframe/group_by/test.rs
- rust/src/measurements/make_private_lazyframe/mod.rs
- rust/src/traits/cast/mod.rs
> Polars: stable key release under approx-zCDP

- python/test/test_polars.py
- rust/src/domains/mod.rs
- rust/src/transformations/make_stable_expr/expr_to_physical/mod.rs
- rust/src/transformations/make_stable_expr/expr_to_physical/test.rs
- rust/src/transformations/make_stable_expr/mod.rs
> Polars: add to_physical transformation

- R/opendp/src/opendp.h
- docs/source/api/user-guide/plugins/index.rst
- python/src/opendp/mod.py
- python/test/test_core.py
- rust/opendp_tooling/src/codegen/r/mod.rs
- rust/src/measures/code/new_privacy_profile.rst
- rust/src/measures/ffi.rs
> add plugin FFI for privacy profiles

- rust/src/accuracy/tail_bounds/test.rs
> update discrete gaussian tail test

- rust/Cargo.toml
Closes #2077
See https://github.com/pola-rs/polars/issues/19063#issuecomment-2397815029
> enable 'raw' feature in hashbrown dependency

- .github/workflows/smoke-test.yml
- python/test/test_polars.py
- rust/src/measurements/make_private_expr/expr_noise/test.rs
- rust/src/transformations/make_stable_expr/expr_sum/mod.rs
> check max_changed_partitions at construction-time

- rust/src/transformations/make_stable_expr/expr_sum/mod.rs
- rust/src/transformations/sum/float/checked/mod.rs
- rust/src/transformations/sum/float/checked/test.rs
- rust/src/transformations/sum/int/checked/ffi.rs
- rust/src/transformations/sum/int/checked/mod.rs
- rust/src/transformations/sum/int/mod.rs
- rust/src/transformations/sum/int/monotonic/ffi.rs
- rust/src/transformations/sum/int/monotonic/mod.rs
- rust/src/transformations/sum/int/ordered/ffi.rs
- rust/src/transformations/sum/int/ordered/mod.rs
- rust/src/transformations/sum/int/split/ffi.rs
- rust/src/transformations/sum/int/split/mod.rs
- rust/src/transformations/sum/mod.rs
> simplify sum traits

- docs/source/getting-started/tabular-data/essential-statistics.ipynb
> expand commentary on accuracy estimation in polars intro

- rust/src/accuracy/polars/test.rs
- rust/src/domains/polars/expr/mod.rs
- rust/src/domains/polars/frame/mod.rs
- rust/src/domains/polars/frame/test.rs
- rust/src/domains/polars/series/mod.rs
- rust/src/measurements/make_private_expr/expr_noise/test.rs
- rust/src/measurements/make_private_expr/test.rs
- rust/src/measurements/make_private_lazyframe/group_by/test.rs
- rust/src/measurements/make_private_lazyframe/postprocess/test.rs
- rust/src/measurements/make_private_lazyframe/select/test.rs
- rust/src/transformations/make_stable_expr/expr_discrete_quantile_score/test.rs
- rust/src/transformations/make_stable_expr/test_helper.rs
- rust/src/transformations/make_stable_lazyframe/filter/test.rs
- rust/src/transformations/make_stable_lazyframe/h_stack/test.rs
> Polars: proof definitions

- docs/source/index.rst
> Add Christchurch Call to list of examples

- rust/opendp_tooling/src/codegen/r/mod.rs
- rust/src/core/ffi.rs
- rust/src/internal/mod.rs
> honest-but-curious function

- docs/source/getting-started/assessing-utility/noise.ipynb
- docs/source/getting-started/tabular-data/grouping.ipynb
- python/src/opendp/context.py
- python/test/test_usability.py
> Polars: error if string given as margin identifier

- python/test/test_core.py
- rust/src/core/ffi.rs
- rust/src/internal/mod.rs
> fix CallbackFn segfault

- python/src/opendp/extras/polars/__init__.py
- rust/src/data/ffi/polars.rs
- rust/src/polars/mod.rs
> Polars: update honest-but-curious note on OnceFrame.lazy

- docs/source/getting-started/tabular-data/counting-queries.ipynb
- docs/source/getting-started/tabular-data/essential-statistics.ipynb
- docs/source/getting-started/tabular-data/grouping.ipynb
- docs/source/getting-started/tabular-data/index.rst
- python/src/opendp/extras/polars/__init__.py
- python/src/opendp/prelude.py
- python/test/test_polars.py
- rust/src/accuracy/code/summarize_polars_measurement.rst
- rust/src/accuracy/polars/mod.rs
- rust/src/accuracy/polars/test.rs
- rust/src/domains/polars/expr/mod.rs
- rust/src/measurements/make_private_expr/expr_noise/test.rs
- rust/src/measurements/make_private_expr/mod.rs
- rust/src/polars/mod.rs
- rust/src/transformations/make_stable_expr/expr_count/mod.rs
- rust/src/transformations/make_stable_expr/expr_count/test.rs
- rust/src/transformations/make_stable_expr/expr_len/mod.rs
- rust/src/transformations/make_stable_expr/expr_sum/mod.rs
- rust/src/transformations/make_stable_expr/mod.rs
> Polars: add len, count, null_count, n_unique

- docs/requirements_notebooks.txt
- python/setup.cfg
> minimum version on randomgen

- rust/Cargo.toml
- rust/src/domains/polars/datetime/mod.rs
- rust/src/domains/polars/mod.rs
- rust/src/domains/polars/series/mod.rs
- rust/src/traits/operations/mod.rs
- rust/src/transformations/make_stable_expr/mod.rs
- rust/src/transformations/make_stable_expr/namespace_str/expr_strptime/mod.rs
- rust/src/transformations/make_stable_expr/namespace_str/expr_strptime/test.rs
- rust/src/transformations/make_stable_expr/namespace_str/mod.rs
> Polars: add strptime

- python/src/opendp/extras/polars/__init__.py
- rust/src/domains/polars/datetime/mod.rs
- rust/src/transformations/make_stable_expr/mod.rs
- rust/src/transformations/make_stable_expr/namespace_dt/expr_datetime_component/mod.rs
- rust/src/transformations/make_stable_expr/namespace_dt/expr_datetime_component/test.rs
- rust/src/transformations/make_stable_expr/namespace_dt/mod.rs
> Polars: add date and time components

- python/src/opendp/context.py
- python/test/context/test_context.py
Test now passes, but I'm not confident that the logic is actually correct.
- Fix #2140
> `split_by_weights` with floats

- python/.coveragerc
- python/src/opendp/_convert.py
- python/src/opendp/_lib.py
- python/src/opendp/context.py
- python/src/opendp/extras/numpy/__init__.py
- python/src/opendp/extras/numpy/_make_np_count/__init__.py
- python/src/opendp/extras/numpy/_make_np_mean/__init__.py
- python/src/opendp/extras/numpy/_make_np_sscp/__init__.py
- python/src/opendp/extras/numpy/_make_np_sum/__init__.py
- python/src/opendp/extras/polars/__init__.py
- python/src/opendp/extras/sklearn/_make_eigendecomposition/__init__.py
- python/src/opendp/extras/sklearn/_make_eigenvalues/__init__.py
- python/src/opendp/extras/sklearn/_make_eigenvector/__init__.py
- python/src/opendp/extras/sklearn/decomposition/__init__.py
- python/src/opendp/mod.py
- python/src/opendp/typing.py
- Fix #1830
None of these would need to be addressed with any urgency, but it would nudge us to improve coverage on future PRs.
> Cover `raise` statements

- docs/source/index.rst
- fix #1971 
- fix #1970 
- fix #1923
- Change them all to past tense for consistency.
>  update users list on docs homepage

- docs/source/_templates/old-version-warning.html
- docs/source/conf.py
- Fix #2152
(I spent a little time trying to get a pure-css solution, but I had some trouble because of wrapping elements around this div.)
> Reposition version warning after page load

- .github/workflows/build.yml
- rust/Cargo.toml
Closes #2201
https://github.com/opendp/opendp/actions/runs/12386133620/job/34573675696
> set MACOSX_DEPLOYMENT_TARGET to fix nightly

- docs/source/api/user-guide/measurements/additive-noise-mechanisms.ipynb
- rust/opendp_tooling/src/bootstrap/docstring.rs
> add backticks around name

- .flake8
- .github/workflows/docs.yml
- docs/README.md
- docs/source/contributing/development-environment.rst
- python/.mypy.ini
> docs: update venv instructions with more descriptive names

- rust/src/polars/mod.rs
> fix: docs.rs build

- docs/source/getting-started/tabular-data/preparing-microdata.ipynb
- python/src/opendp/extras/polars/__init__.py
- python/test/test_polars.py
- rust/src/transformations/make_stable_lazyframe/mod.rs
- rust/src/transformations/make_stable_lazyframe/select/mod.rs
- rust/src/transformations/make_stable_lazyframe/select/test.rs
> feat: Polars select transformation

- docs/404.html
- docs/source/api/user-guide/measurements/index.rst
- docs/source/theory/resources.rst
These are all small, so thought it'd be ok to lump them together.
- Fix #2248 
- Fix #2247 
- Fix #2237 
- Fix #2215
> docs: better 404 page + better docs links

- python/test/test_ast.py
For the reviewer:
- Confirmation that none of the `TODO`s need attention right now?
- ... but any one of them would be a small improvement, and something we might point a new dev at for a warm up?
> testing: Clean up AST tests

- .github/workflows/smoke-test.yml
- R/opendp/.lintr
- R/opendp/R/mod.R
- R/opendp/R/typing.R
- R/opendp/tests/testthat/test-typing.R
- R/opendp/tools/configure.R
- docs/source/.lintr
- rust/opendp_tooling/src/codegen/r/r.rs
- rust/opendp_tooling/src/codegen/test.rs
- rust/src/transformations/make_stable_lazyframe/select/test.rs
> fix: compatibility with R lintr 3.2

- docs/source/api/user-guide/combinators/compositors.rst
- python/src/opendp/mod.py
> docs: Add documentation on Queryable

- docs/source/api/user-guide/polars/expressions/manipulation.ipynb
- python/test/test_polars.py
- rust/Cargo.toml
- rust/src/transformations/make_stable_expr/expr_replace/mod.rs
- rust/src/transformations/make_stable_expr/expr_replace/test.rs
- rust/src/transformations/make_stable_expr/expr_replace_strict/mod.rs
- rust/src/transformations/make_stable_expr/expr_replace_strict/test.rs
- rust/src/transformations/make_stable_expr/mod.rs
> feat: Polars replace

- docs/source/api/user-guide/polars/expressions/manipulation.ipynb
- rust/src/domains/polars/expr/mod.rs
- rust/src/domains/polars/series/mod.rs
- rust/src/transformations/make_stable_expr/expr_drop_nan_or_null/mod.rs
- rust/src/transformations/make_stable_expr/expr_drop_nan_or_null/test.rs
- rust/src/transformations/make_stable_expr/expr_fill_nan/mod.rs
- rust/src/transformations/make_stable_expr/expr_fill_nan/test.rs
- rust/src/transformations/make_stable_expr/expr_fill_null/mod.rs
- rust/src/transformations/make_stable_expr/expr_fill_null/test.rs
- rust/src/transformations/make_stable_expr/expr_filter/mod.rs
- rust/src/transformations/make_stable_expr/expr_filter/test.rs
- rust/src/transformations/make_stable_expr/mod.rs
- rust/src/transformations/make_stable_lazyframe/filter/mod.rs
> feat: expression filtering

- docs/source/api/user-guide/polars/data-types.ipynb
- docs/source/api/user-guide/polars/expressions/manipulation.ipynb
- python/src/opendp/extras/polars/__init__.py
- python/test/test_polars.py
- rust/opendp_tooling/src/codegen/r/c.rs
- rust/opendp_tooling/src/codegen/r/mod.rs
- rust/opendp_tooling/src/codegen/r/r.rs
- rust/src/domains/ffi.rs
- rust/src/domains/polars/categorical/ffi.rs
- rust/src/domains/polars/categorical/mod.rs
- rust/src/domains/polars/enum/ffi.rs
- rust/src/domains/polars/enum/mod.rs
- rust/src/domains/polars/enum/test.rs
- rust/src/domains/polars/mod.rs
- rust/src/domains/polars/series/ffi.rs
- rust/src/domains/polars/series/mod.rs
- rust/src/ffi/util.rs
- rust/src/transformations/make_stable_expr/expr_cast/mod.rs
- rust/src/transformations/make_stable_expr/expr_cast/test.rs
- rust/src/transformations/make_stable_expr/expr_to_physical/mod.rs
> feat: polars enum dtype

- python/src/opendp/extras/polars/__init__.py
- Consider this to resolve #2295 --
- Adding automatic checks for this seems like overkill, so I've closed #2300
> docs: Add missing backticks

- python/src/opendp/extras/polars/__init__.py
- python/test/test_polars.py
- rust/opendp_tooling/src/codegen/r/mod.rs
- rust/src/domains/ffi.rs
- rust/src/domains/polars/array/ffi.rs
- rust/src/domains/polars/array/mod.rs
- rust/src/domains/polars/mod.rs
- rust/src/domains/polars/series/ffi.rs
- rust/src/domains/polars/series/mod.rs
- rust/src/ffi/util.rs
- rust/src/measurements/make_private_expr/expr_report_noisy_max/mod.rs
- rust/src/transformations/make_stable_expr/expr_discrete_quantile_score/mod.rs
- rust/src/transformations/make_stable_expr/mod.rs
- rust/src/transformations/make_stable_expr/namespace_arr/mod.rs
- rust/src/transformations/make_stable_expr/namespace_arr/test.rs
> feat: polars array dtype

- python/test/integration/test_quantile.py
- python/test/test_trans.py
- rust/src/domains/polars/array/ffi.rs
- rust/src/measurements/mod.rs
- rust/src/measurements/private_quantile/ffi.rs
- rust/src/measurements/private_quantile/mod.rs
- rust/src/measurements/private_quantile/test.rs
- rust/src/transformations/make_stable_expr/namespace_arr/mod.rs
- rust/src/transformations/mod.rs
- rust/src/transformations/quantile_score_candidates/mod.rs
> feat: make_private_quantile

- docs/source/index.rst
> Update use case list

- rust/src/measurements/make_private_expr/expr_index_candidates/mod.rs
- rust/src/measurements/make_private_expr/expr_noise/mod.rs
- rust/src/measurements/make_private_expr/expr_report_noisy_max/mod.rs
- rust/src/polars/mod.rs
- rust/src/polars/test.rs
- rust/src/transformations/make_stable_expr/expr_discrete_quantile_score/mod.rs
- rust/src/transformations/make_stable_expr/expr_discrete_quantile_score/plugin_dq_score.rs
> fix: Rust quantile schema mismatch

- rust/src/combinators/amplify/mod.rs
- rust/src/transformations/cast_metric/traits.rs
> docs: improve proof definition coverage

- rust/src/transformations/impute/mod.rs
- rust/src/transformations/impute/test.rs
> fix: tighten imputer domain descriptors

- python/test/test_polars.py
- rust/src/transformations/make_stable_expr/expr_binary/mod.rs
- rust/src/transformations/make_stable_expr/expr_binary/test.rs
Fix #2196
Makes weighted queries possible, for use-case.
> feat: binary function expressions

- python/src/opendp/mod.py
- python/test/test_binary_search.py
- rust/src/ffi/dispatch.rs
Close #2365
This also cleans up the existing code.
> feat: show errors when binary search type inference fails

- rust/src/transformations/make_stable_expr/namespace_str/expr_strptime/make_expr_strptime.tex
- rust/src/transformations/make_stable_expr/namespace_str/expr_strptime/pseudocode/make_expr_strptime.py
> feat: prove make_expr_strptime

- rust/src/measurements/noise/distribution/geometric/mod.rs
Close #2379
We key into whether the binary is a debug or release build, and monomorphize fewer types when the binary is a debug build to make it faster to build the debug binary when developing. The additional types present in a release build triggered the compiler error.
> fix: ConstantTimeGeometric release build

- python/src/opendp/context.py
- python/src/opendp/mod.py
- python/test/context/test_context.py
- rust/src/measurements/randomized_response/make_randomized_response.tex
- rust/src/measurements/randomized_response/make_randomized_response_bool.tex
- rust/src/measurements/randomized_response/mod.rs
- rust/src/measurements/randomized_response/pseudocode/make_randomized_response.py
- rust/src/measurements/randomized_response/pseudocode/make_randomized_response_bool.py
- rust/src/measurements/randomized_response/test.rs
> feat: improve usability of randomized response mechanisms

- rust/src/domains/polars/frame/find_min_covering.tex
- rust/src/domains/polars/frame/get_margin.tex
- rust/src/domains/polars/frame/mod.rs
- rust/src/domains/polars/frame/pseudocode/find_min_covering.py
- rust/src/domains/polars/frame/pseudocode/get_margin.py
> feat: prove `get_margin` and `find_min_covering`

- .flake8
> Flake8 should ignore tools venv

- python/src/opendp/extras/sklearn/decomposition/__init__.py
(To fix CI, please merge #2394 first, and then update this PR.)
- Fix #2367
> add link to PCA source

- python/src/opendp/_lib.py
> If envvar is set, show more info

- rust/src/domains/mod.rs
- rust/src/measurements/canonical_noise/mod.rs
- rust/src/measurements/noise/nature/float/mod.rs
- rust/src/measurements/noise_threshold/nature/float/mod.rs
- rust/src/measurements/noisy_top_k/exponential/mod.rs
- rust/src/measurements/noisy_top_k/gumbel/mod.rs
- rust/src/traits/operations/mod.rs
> fix: always default to include inf in float domains

- .github/workflows/smoke-test.yml
- docs/source/getting-started/statistical-modeling/index.rst
- docs/source/getting-started/statistical-modeling/synthetic-data.rst
- docs/source/getting-started/tabular-data/contingency-tables.rst
- docs/source/getting-started/tabular-data/index.rst
- python/src/opendp/extras/mbi/_aim/__init__.py
- python/src/opendp/extras/mbi/_fixed/__init__.py
- python/src/opendp/extras/mbi/_mst/__init__.py
- python/src/opendp/extras/mbi/_table/__init__.py
- python/test/test_interactive.py
- python/test/test_meas.py
- rust/src/measurements/noisy_top_k/gumbel/test.rs
- rust/src/transformations/make_stable_expr/expr_replace_strict/mod.rs
> docs: contingency tables and synthetic data

- docs/source/api/user-guide/transformations/aggregation-mean.rst
> Remove old, unneeded comment

- docs/source/api/user-guide/measurements/approximate-laplace-projection.ipynb
- docs/source/api/user-guide/measurements/index.rst
- rust/src/measurements/alp/mod.rs
- rust/src/measurements/alp/test.rs
> docs: make_alp_queryable
