rust/opendp-ffi/src/core.rs, rust/opendp-ffi/src/trans.rs, rust/opendp/src/core.rs, rust/opendp/src/lib.rs, rust/opendp/src/meas/mod.rs, rust/opendp/src/traits.rs, rust/opendp/src/trans/dataframe.rs, rust/opendp/src/trans/mod.rs
Linked to #30 
Still need to implement passing hints over FFI.
Suffers from #33.
Stability and privacy relations are oftentimes specified in terms of a constant.  
In these cases, it is possible to bundle a forward and backward map with the stability relation, to construct hints automatically.
=> chaining hints

python/opendp.py, python/test.py, rust/opendp-ffi/src/data.rs, rust/opendp-ffi/src/dispatch.rs, rust/opendp-ffi/src/meas.rs, rust/opendp/Cargo.toml, rust/opendp/src/dist.rs, rust/opendp/src/lib.rs, rust/opendp/src/meas/gaussian.rs, rust/opendp/src/meas/geometric.rs, rust/opendp/src/meas/laplace.rs, rust/opendp/src/meas/mod.rs, rust/opendp/src/traits.rs
Ported, with modifications throughout, from SmartNoise.
- introduces dependencies on openssl and gmp/mpfr
- adds feature flags to disable gmp/mpfr
- restructure meas submodule
- reference new samplers from laplace, geometric and gaussian mechanisms
New samplers:
- standard bernoulli
- bernoulli
- standard uniform (over float types)
- uniform (over float types)
- rademacher (over signed types)
- censored standard geometric (accumulates tail of probability < ~2^-52 into fully-saturated 1022)
- censored geometric
- laplace (mpfr and non-mpfr) (over float types)
- gaussian (mpfr and non-mpfr) (over float types)
=> laplace/gaussian/geometric floating-point-safe samplers

python/example/stability_mechanism.py, python/src/opendp/mod.py, python/test/test_opendp.py, rust/opendp-ffi/src/core.rs, rust/opendp-ffi/src/data.rs, rust/opendp-ffi/src/trans.rs, rust/opendp-ffi/src/util.rs, rust/opendp/src/error.rs, rust/opendp/src/meas/stability.rs
closes #77 
- adds a new error variant "RelationDebug" to pass messages to Python, as well as a measurement_check function
* the error variant is likely temporary
- refactored python data loader to have more type checking and support more data types
- data loader/unloader for tuples via void* slices
* modified descriptor parser to keep tuples together in one descriptor, instead of just splitting by comma
- stability relation example works again
- OdpException.cls -> .variant
- OpenDP.py_to_obj now takes an optional type argument for explicit typing
- print out a warning for errors masked by obj_to_py failures
- adds de-allocation methods for strings and bools
- de-allocate relation checks, ffi slices and type strings once parsed into python
=> Expanded data loaders/unloaders

python/example/test.py, python/src/opendp/mod.py, python/test/test_errors.py, rust/opendp-ffi/src/core.rs, rust/opendp-ffi/src/data.rs, rust/opendp-ffi/src/dispatch.rs, rust/opendp-ffi/src/lib.rs, rust/opendp-ffi/src/meas.rs, rust/opendp-ffi/src/trans.rs, rust/opendp-ffi/src/util.rs, rust/opendp/src/core.rs, rust/opendp/src/data.rs, rust/opendp/src/error.rs, rust/opendp/src/lib.rs, rust/opendp/src/meas/gaussian.rs, rust/opendp/src/meas/geometric.rs, rust/opendp/src/meas/laplace.rs, rust/opendp/src/meas/stability.rs, rust/opendp/src/samplers.rs, rust/opendp/src/trans/count.rs, rust/opendp/src/trans/dataframe.rs, rust/opendp/src/trans/manipulation.rs, rust/opendp/src/trans/mod.rs, rust/opendp/src/trans/sum.rs
Closes #67 
- add From impls for common error handling paths. Example:
* in opendp-ffi/src/trans.rs, `count::Count::<MI, MO, T>::make().into()` builds an `FfiResult<*mut FfiTransformation>`
- Add `ExplainUnwrap` trait for `.unwrap_assert()` and `.unwrap_test()`, to make it easier to identify leftover `.unwrap()`s
* By convention, replace unwrap with unwrap_test in tests
* By convention, replace unwrap with unwrap_assert in library code where panics should be unreachable
- Replace `assert_eq!`, `assert!`, `unwrap`, `expect` with error handling throughout the library
* there are still some cases that can cause panics- these should now be easy to identify
- Add `try_!` macro to substitute for ? when the return is FfiResult. This is based on the deprecated std try! macro.
- Add `try_as_ref!` …
=> constructor error handling

rust/opendp-ffi/src/trans.rs, rust/opendp/src/trans/mean.rs, rust/opendp/src/trans/mod.rs, rust/opendp/src/trans/sum.rs, rust/opendp/src/trans/variance.rs
Closes #68.
- BoundedVariance transformation
- BoundedCovariance transformation
- Use higher ranked trait bounds to clean up extra clones in aggregators
=> BoundedVariance & BoundedCovariance

rust/opendp-ffi/src/core.rs, rust/opendp/src/any.rs, rust/opendp/src/core.rs, rust/opendp/src/dist.rs, rust/opendp/src/error.rs, rust/opendp/src/interactive.rs, rust/opendp/src/lib.rs, rust/opendp/src/poly.rs, rust/opendp/src/traits.rs
Closes #80.
I kept this as a fairly conservative change. Most of the code is in separate modules (`any` and `interactive`). Aside from a few trait bounds, the existing types and logic stay the same for non-interactive Measurements and Transformations.
If/when we're happy with this, we can migrate the FFI wrappers to use the type-erased (AnyXXX) approach in #88.
* Created type-erased versions of Measurement/Transformation component types.
* Added type-erasing transformers to Measurement/Transformation.
* Defined generic Queryable abstraction.
* Implemented make_adaptive_composition() constructor.
* Added unit tests.
* Created a separate abstraction for polymorphic operations.
=> Interactive Measurements (and type-erased component types)

rust/opendp-ffi/src/any.rs, rust/opendp-ffi/src/core/mod.rs, rust/opendp-ffi/src/data/mod.rs, rust/opendp-ffi/src/dispatch.rs, rust/opendp-ffi/src/util.rs
Closes #97.
Note that, snuck into this change, there's a cfg thing in dispatch.rs so that dev and test builds will compile with a limited set of types for faster monomorphization. If this is a problem, I'm happy to back it out and keep it in my own clone.
* Cleaned up tuple logic.
* Added AnyObject support to type dispatch.
* Wrote some unit tests to cover tuple cases.
* Made a cfg with a stripped-down set of types for fast compilation of dev target.
* Picked up suggested tweaks from #96 PR review.
=> Fixed tuple issues in opendp_data__object_as_slice()

rust/opendp-ffi/Cargo.toml
Closes #100 (again).
The opendp crate is a dependency of opendp-ffi, and opendp-ffi referenced opendp without `default-features = false`. This updates the opendp dependency to have no default features, re-exports the opendp features, and then enables the same default features by default in the opendp-ffi crate.
This time I tested the cargo tree output to ensure that `gmp-mpfr-sys` and `rug` do not exist in the dependency tree when the `--no-default-features` flag is set:
`cargo tree | grep -E '(rug|gmp)'`
```
├── gmp-mpfr-sys v1.3.1
├── rug v1.10.0
│   ├── gmp-mpfr-sys v1.3.1 (*)
```
vs 
`cargo tree --no-default-features | grep -E '(rug|gmp)'`
```
```
=> re-export features from opendp crate in opendp-ffi

rust/opendp-ffi/Cargo.toml, rust/opendp/Cargo.toml, rust/opendp/src/samplers.rs
Closes #100 (again).
This places openssl behind a default `use-openssl` feature flag. Using --no-default-features will now remove openssl and gmp/mpfr from the dependencies.
=> use-openssl crate feature

rust/opendp-ffi/src/any.rs, rust/opendp/src/core.rs, rust/opendp/src/dom.rs, rust/opendp/src/poly.rs
Closes #87
This also drops the `any.rs` Bool trait and PhantomData in favor of const generics.
=> close #87, make member fallible

rust/opendp-ffi/src/meas/gaussian.rs, rust/opendp-ffi/src/meas/geometric.rs, rust/opendp-ffi/src/meas/laplace.rs, rust/opendp-ffi/src/meas/stability.rs, rust/opendp-ffi/src/trans/cast.rs, rust/opendp-ffi/src/trans/clamp.rs, rust/opendp-ffi/src/trans/count.rs, rust/opendp-ffi/src/trans/mean.rs, rust/opendp-ffi/src/trans/sum.rs, rust/opendp-ffi/src/trans/variance.rs, rust/opendp-ffi/src/util.rs, rust/opendp/src/core.rs, rust/opendp/src/dist.rs, rust/opendp/src/lib.rs, rust/opendp/src/meas/gaussian.rs, rust/opendp/src/meas/geometric.rs, rust/opendp/src/meas/laplace.rs, rust/opendp/src/meas/stability.rs, rust/opendp/src/traits.rs, rust/opendp/src/trans/cast.rs, rust/opendp/src/trans/clamp.rs, rust/opendp/src/trans/count.rs, rust/opendp/src/trans/dataframe.rs, rust/opendp/src/trans/manipulation.rs, rust/opendp/src/trans/mean.rs, rust/opendp/src/trans/sum.rs, rust/opendp/src/trans/variance.rs
Closes #33 
Added traits:
- `TO: RoundCast<TI>` cast from vi: TI to vo: TO with rounding to nearest, ties to even
- `TO: InfCast<TI>` cast where vi: TI <= vo: TO
- `TO: ExactIntCast<TI>` casting for integers where vi: TI == vo: TO, and vo < `TO::MAX_CONSECUTIVE`
Removed `DistanceCast` trait, which still had some edge cases that would round down:
1. When casting from f64 to f32
2. When casting an int greater than 2^p to nearest, ties to even float with precision p
Switch DistanceConstant to use InfCast, instead of DistanceCast.
Remove num::NumCast from most places in the library, in favor of the more explicit cast traits with situationally-appropriate cast behavior.
This allows TO on count queries to be float-valued, so that you can run float-mechanisms on them. We might want to think more …
=> Explicit casting traits

rust/opendp-ffi/src/trans/count.rs, rust/opendp-ffi/src/trans/mean.rs, rust/opendp-ffi/src/trans/sum.rs, rust/opendp-ffi/src/trans/variance.rs, rust/opendp/src/traits.rs, rust/opendp/src/trans/count.rs, rust/opendp/src/trans/mean.rs, rust/opendp/src/trans/sum.rs, rust/opendp/src/trans/variance.rs
Closes #178
Adjusts:
- make_bounded_sum (by check)
- make_bounded_sum_n (by saturation)
- make_bounded_variance (by check)
- make_bounded_covariance (by check)
- make_bounded_mean (by check)
- make_count_by_categories (by saturation)
- make_count_by (by saturation)
(by check) means checked arithmetic is performed to compute the maximum/minimum value that may happen at runtime. If the checked arithmetic fails, the computation may fail, so the constructor fails to build the transformation.
(by saturation) means the function itself uses saturating math instead of wrapping or panicking math, which preserves the privacy semantics.
=> Properly handle overflows in aggregators

.github/assert_version.py, .github/workflows/release.yml, .github/workflows/smoke-test.yml
I'm using this piece from the twine api to feed the api key into twine via CI: https://pypi.org/help/#apitoken
=> fix pypi token, move VERSION check to release.yml

.github/workflows/docs.yml, .github/workflows/sync-branches.yml
There was a bogus status check in sync-branches.yml; this has been moved to docs.yml.
Note: This means that we can't run docs.yml manually, because it needs to check this status, but that's probably not a big deal.
=> Moved bogus status check in workflows.

.github/workflows/sync-branches.yml
Previously omitted from sync-branches workflow, this pushes the updated branches to origin.
=> Push updated branches.

.github/workflows/docs.yml
When checking out the repo in the docs workflow, we need to fetch all refs (in addition to including in smv_remote_whitelist config variable).
=> Fetch all refs for docs.

.github/workflows/release.yml
* Add sleep to allow crates.io index to settle before publishing opendp-ffi
=> Fix crate publishing issues

.github/workflows/release.yml
This picks up the final fixes we made to get crate publishing to work. (Going against proper procedure, I made these changes directly on the release branch, so they need to be picked up in main.)
* Added more sleep to allow crates.io index to settle before publishing opendp-ffi.
* Specified explicit features (omitting python gen) when calling cargo publish on opendp-ffi.
=> Fix remaining crate publishing issues

python/src/opendp/trans.py, python/test/test_trans.py, rust/opendp-ffi/build/main.rs, rust/opendp-ffi/src/data/bootstrap.json, rust/opendp-ffi/src/meas/bootstrap.json, rust/opendp-ffi/src/trans/bootstrap.json, rust/opendp-ffi/src/trans/resize.rs, rust/opendp/src/trans/resize/mod.rs
Closes #230 
I made the resize transform generic in the library core, but can only provide an interface for a single domain at a time from FFI. A next step would be adding FFI functions for constructing domains themselves. A user could then pass these domains into the resize constructor as an AnyDomain. See https://github.com/opendp/opendp/issues/232
=> atomic domain in resize transform

python/src/opendp/mod.py, python/test/test_core.py, rust/opendp-ffi/src/dispatch.rs, rust/opendp/src/trans/resize/mod.rs
Closes #237 
Adds a general binary search algorithm to python to solve for free parameters in computation chains.
Adds distance maps to the resize transformation. The library was finding a very strange loosening.
Allows _free to fail when the interpreter is shutting down at the end of the program.
=> Binary search utilities

rust/opendp-ffi/src/any.rs, rust/opendp/src/comb/chain/mod.rs, rust/opendp/src/core.rs, rust/opendp/src/dist.rs, rust/opendp/src/dom.rs, rust/opendp/src/poly.rs
Closes #201.
Continuation of #263.
This adds Debug trait bounds to domains, metrics and measures. When you attempt to chain incompatible measurements or operations, you can see how they differ. This doesn't capture type information or parameters contained within the domain. This PR differs from the previous one in that it omits parameters in the errors, which avoids requiring debug on all downstream types (everything is downstream).
Sample errors:
When you fail to clamp.
```
opendp.mod.OpenDPException: DomainMismatch("Intermediate domains don't match.
output_domain: VectorDomain(AllDomain())
input_domain:  VectorDomain(BoundedDomain())
")
```
When you fail to resize.
```
opendp.mod.OpenDPException: DomainMismatch("Intermediate domains don't match.
output_domain: …
```
=> capture Debug trait in AnyBoxBase (4) 

python/src/opendp/accuracy.py, python/test/test_accuracy.py, rust/opendp-ffi/build/main.rs, rust/opendp-ffi/build/python.rs, rust/opendp-ffi/src/accuracy/bootstrap.json, rust/opendp-ffi/src/accuracy/mod.rs, rust/opendp-ffi/src/lib.rs, rust/opendp/src/accuracy.rs, rust/opendp/src/lib.rs
Closes #274 
Adds utilities for converting between accuracy estimates and noise scales for laplacian and gaussian noise.
The laplacian noise estimate can also be used for the geometric distribution.
We might want to think about renaming `make_base_geometric` to `make_base_discrete_laplace` at some point to make this more obvious.
One could make the argument that you should take the ceil of the geometric accuracy, because the support is discrete ...but on the other hand, the probabilities are still approximately continuous, so I don't think this is necessary. Due to this, I have dropped the ceil when porting from Smartnoise-Core.
=> accuracy utilities

docs/source/quickstart/index.rst, docs/source/user/getting-started.rst
=> 268 quickstart

docs/source/more.rst, docs/source/resources/index.rst
closes #272
I took a quick swing at at least putting links to papers, etc. onto a Resources page. The formatting is extremely minimal and looks like this right now:
I'm not sure how fancy we should get. At minimum, we should probably link the titles to the papers like they do at https://differentialprivacy.org/resources/ (they also link the author names, which would be more work):
We could also try to use full on citations and a Sphinx extension where we keep all these in Bibtex format. Probably overkill, I'd say.
Under the "Papers" section I left comments from @Shoeboxam in parentheses. We can take these out or otherwise rework them.
=> add Resources section #272

docs/source/examples/notebooks.rst
Instead of a raw link to GitHub, I added some surrounding text so it looks nicer.
More importantly, I also linked to Binder so people can try the notebooks from their browser.
For now, the Binder link doesn't have a branch specified so it'll default to "main" (the default) but as discussed in #285 once we cut a release, we can specify "stable" as the branch.
=> clean up notebook example link, add Binder link #285

docs/source/_templates/versioning.html
Closes #311.
* Hacked Jinja template to fix sorting for RC versions
TADA!
At the same time, I feel some shame for this hack. Will break when numbers get above 10.
Screenshot:
=> Docs version list sorting

rust/opendp-ffi/src/lib.rs, rust/opendp-ffi/src/meas/mod.rs, rust/opendp-ffi/src/trans/mod.rs
The FFI layer is expecting the existence of functions that have been cfg'ed! This missed testing because all of our builds used the "contrib" feature implicitly. The "contrib" feature is enabled by default for debug builds via the dev-dependencies.
Finishes #306.
=> add contrib feature flag to FFI

rust/opendp-ffi/src/any.rs, rust/opendp/src/core.rs, rust/opendp/src/meas/gaussian/mod.rs, rust/opendp/src/meas/laplace/mod.rs, rust/opendp/src/samplers.rs, rust/opendp/src/trans/resize/mod.rs
Closes #182. It was possible to sample -0 in the non-MPFR laplace sampler and induce a NaN.
Closes #345. With this change, I think the continuous noise samplers are no longer subject to major floating-point attacks. I am not aware of any significant floating point issues in the continuous noise samplers, beyond some minor rounding in preprocessing. We will of course need to do more vetting.
For Laplace noise we have Von-Neumann's exact standard exponential sampler from MPFR, and add a sign non-disruptively with rademacher noise to get standard laplacian noise. The input is divided by scale before adding the standard laplacian noise. We now have a DP release without scaling the noise. Postprocess the DP release back to the original coordinates by multiplying by scale.
For gaussian noise we …
=> fix continuous noise samplers

docs/source/user/transformation-constructors.rst, python/src/opendp/trans.py, python/test/test_trans.py, rust/opendp-ffi/src/trans/bootstrap.json, rust/opendp-ffi/src/trans/impute.rs, rust/opendp/src/trans/impute/mod.rs
Closes #347 
Adds a transformation that drops null values (an alternative to constant imputation). Requested by DPCreator.
=> add `make_drop_null` transformation

python/src/opendp/_convert.py, python/src/opendp/_lib.py, python/src/opendp/trans.py, python/test/test_trans.py, rust/opendp-ffi/build/python_typemap.json, rust/opendp-ffi/build/type_hierarchy.json, rust/opendp-ffi/src/dispatch.rs, rust/opendp-ffi/src/trans/bootstrap.json, rust/opendp-ffi/src/trans/index.rs, rust/opendp-ffi/src/trans/mod.rs, rust/opendp-ffi/src/util.rs, rust/opendp/src/traits.rs, rust/opendp/src/trans/index/mod.rs, rust/opendp/src/trans/mod.rs
Closes #320 
This adds three transformations:
- `make_find` finds the index of a category for each value in a hashable vector
- `make_find_bin` finds the edge index for each value in a numeric vector
- `make_index` indexes into a category set
The `make_find` and `make_index` transformations can be used for relabeling and merging categories.
The `make_find_bin` can be used to bin numeric data. If you then chain with `make_index` then you can also label bins.
=> relabeling, binning, indexing

docs/source/user/application-structure.rst, python/test/test_trans.py, rust/opendp/src/trans/resize/mod.rs
Closes #355 
This spawns a new issue: for the use-case when N is known, it is impossible to establish SizedDomain without incurring a 2x penalty.
=> fix resize relation

rust/opendp/Cargo.toml, rust/opendp/src/error.rs, rust/opendp/src/samplers.rs
Related to #74.
Based on #75.
Adds a test for the biased bernoulli sampler.
Adds some plots to visualize common probability distributions.
=> sampler correctness checks

python/src/opendp/_convert.py, python/src/opendp/typing.py, python/test/test_convert.py, python/test/test_meas.py, python/test/test_typing.py
closes #393 
- Type inference for 0- and 1-dimensional arrays
- Automatically unpack 0- and 1- dimensional arrays into python scalars and lists
=> support for numpy dtypes

python/src/opendp/_convert.py, python/src/opendp/_lib.py
Closes #397 
This adds a `__del__` destructor for AnyObjects, so that constructor arguments, invoke arguments/returns, and check arguments are freed. 
It also adds some python refcounting manipulation to prevent the AnyObjects used to build HashMaps from being freed too early, or to be double-freed.
=> __del__ destructor for AnyObjects

rust/opendp/src/samplers.rs, rust/opendp/src/traits/arithmetic.rs
Closes #401 
The order of operations caused a greater tendency for overflow- even when scale is as large as `.0001`.
This PR also adjusts the error messages when you do overflow.
=> avoid overflow in geometric mechanism

CHANGELOG.md, docs/source/user/combinator-constructors.rst, docs/source/user/measurement-constructors.rst, docs/source/user/transformation-constructors.rst, python/example/README.md, rust/opendp-ffi/Cargo.toml, rust/opendp/Cargo.toml
- Updated changelog
- Close #169, updated rust edition to 2021
- Close #391 
- Close #406, fixed warnings from rust 1.56
- Updated documentation for the index transforms, randomized response, privacy amplification
- Updated documentation for floating-point vulnerabilities
Once unblocked, update this PR with respective documentation/changes and undraft.
=> preparation for v0.4.0

.github/workflows/release.yml, .github/workflows/smoke-test.yml, CHANGELOG.md, rust/Cargo.toml, tools/publish_tool.py, tools/release_tool.py, tools/rust_build.sh
Fixes #439. Thanks @Shoeboxam for doing the core of this!
* Add target option to rust_build.sh
* Extend release.yml to cross-compile aarch64 and merge into universal binary
* Fix some Cargo.toml paths missed in #396
* Update CHANGELOG
=> Support aarch64-apple-darwin

docs/source/conf.py, python/src/opendp/_lib.py, rust/Cargo.toml
Closes #433
Closes #432
This also changes the behavior of `OPENDP_HEADLESS`. The library will always attempt to load `lib`, but if `OPENDP_HEADLESS` is set, failure to load `lib` is not considered an error. This is so that headless may be set in sphinx multiversion via `conf.py`, but the smoke-test doctests still work.
=> Fix docs.rs documentation and historical python documentation

docs/source/user/application-structure.rst, python/src/opendp/mod.py, python/src/opendp/typing.py, python/test/test_binary_search.py, python/test/test_core.py, python/test/test_trans.py
Closes #443 
Closes #362 
- Fixes an infinite loop due to floating-point roundoff when distance to nearest neighbor is greater than tolerance.
- Removes the tolerance argument, because the algorithm terminates when the argument stops changing.
- Bounds on `binary_search` have been made optional via exponential search
- Exponential search bounds increase magnitudes incrementally, which avoids issues with overflow
- Exponential search bounds should converge in fewer steps, under the assumption that ideal parameters are typically distributed closer to zero
- Added a T argument to specify expected type 
* T is also inferred by catching TypeErrors and "No match" FFI errors
* Replaces AssertionErrors that have to do with typing with more informative TypeErrors
=> binary search fixes

.github/workflows/smoke-test.yml, docs/source/developer/development-environment.rst, rust/Cargo.toml, rust/src/accuracy/mod.rs, rust/src/interactive.rs, rust/src/lib.rs, rust/src/meas/mod.rs, rust/src/poly.rs, rust/src/samplers.rs, rust/src/traits/arithmetic.rs, rust/src/traits/cast.rs
* fix the `--no-default-features` cargo flag
* primarily used for easy windows builds
* smoke-test now checks that the `--no-default-features` flag works
* don't add opendp as a dev-dependency of opendp to enable the untrusted flag by default when testing
* feature configuration wasn't being passed forward into the secondary opendp crate
* therefore the secondary opendp crate re-introduces dependencies on openssl and rug
* add cfg markup to all tests throughout the library that depend on untrusted
* expanded the Development Environment documentation
* fixes #400
=> windows build fix, development environment documentation

docs/source/user/transformation-constructors.rst, python/src/opendp/trans.py, python/test/test_trans.py, rust/src/trans/bootstrap.json, rust/src/trans/cast_metric/mod.rs, rust/src/trans/cast_metric/traits.rs, rust/src/trans/resize/ffi.rs, rust/src/trans/resize/mod.rs
See #357. Doesn't close.
Refactors the resize transformation to shuffle when necessary, in accordance with the ordered-ness of the input and output metric.
=> handle ordering in resize

docs/source/user/application-structure.rst, docs/source/user/combinator-constructors.rst, python/src/opendp/mod.py, python/src/opendp/trans.py, python/test/test_binary_search.py, python/test/test_comb.py, python/test/test_trans.py, rust/src/comb/amplify/mod.rs, rust/src/meas/laplace/mod.rs, rust/src/trans/bootstrap.json, rust/src/trans/mean/ffi.rs, rust/src/trans/mean/mod.rs, rust/src/trans/sum/float/checked/mod.rs, rust/src/trans/sum/float/ordered/mod.rs, rust/src/trans/variance/mod.rs
Closes #470
Simplifies the mean aggregator to a simple chaining of the `sized_bounded_sum` and `lipschitz_mul` transformations.
=> simplify mean to be a lipschitz extension of sum

python/src/opendp/meas.py, python/src/opendp/typing.py, python/test/test_meas.py, rust/src/accuracy/mod.rs, rust/src/ffi/any.rs, rust/src/ffi/util.rs, rust/src/meas/bootstrap.json, rust/src/meas/gaussian/ffi.rs, rust/src/meas/gaussian/mod.rs, rust/src/measures/mod.rs
This minimally introduces ZeroConcentratedDivergence into OpenDP. Caster combinators and compositors are subject to future PRs.
=> ZeroConcentratedDivergence measure; parameterize `base_gaussian`

docs/source/user/combinator-constructors.rst, python/src/opendp/_lib.py, python/src/opendp/meas.py, python/src/opendp/mod.py, python/src/opendp/trans.py, python/src/opendp/typing.py, python/test/test_comb.py, python/test/test_trans.py, python/test/test_typing.py, rust/src/comb/chain/mod.rs, rust/src/comb/compose/ffi.rs, rust/src/domains/mod.rs, rust/src/ffi/any.rs, rust/src/ffi/util.rs, rust/src/meas/bootstrap.json, rust/src/measures/mod.rs, rust/src/metrics/mod.rs, rust/src/trans/bootstrap.json, rust/src/trans/count/mod.rs, rust/src/trans/lipschitz_mul/mod.rs, rust/src/trans/resize/ffi.rs, rust/src/trans/resize/mod.rs
* Adds a utility function to set the default int type, and default float type in the python bindings.
* From the `set_default_int_type and set_default_float_type` commit.
* Closes #431
* Renames the rust function `make_resize_constant` to `make_resize`, to be consistent with python
* Adjust the FFI for `make_*resize` such that `TA` is the last type argument
* Adds a check to `RuntimeType.infer` to ensure that the lists are homogeneous
* Prevents a potential segfault if the input list has mixed types 
* Adjusts the Debug impl for domains, metrics and measures to include the type name
=> QOL adjustments; python utility to specify default atomic type

docs/source/user/measurement-constructors.rst, python/src/opendp/meas.py, python/test/test_meas.py, rust/src/accuracy/mod.rs, rust/src/meas/bootstrap.json, rust/src/meas/discrete_gaussian/ffi.rs, rust/src/meas/discrete_gaussian/mod.rs, rust/src/meas/discrete_laplace/cks20/mod.rs, rust/src/meas/discrete_laplace/mod.rs, rust/src/meas/mod.rs
Closes #186 
This extends the discrete laplace PR to provide a constructor for the discrete gaussian mechanism.
In this implementation, I simply use the Rational type from the rug wrapper for GMP to avoid fixed-point complications.
=> add `make_base_discrete_gaussian` constructor

rust/src/traits/samplers/bernoulli/mod.rs, rust/src/traits/samplers/cks20/mod.rs, rust/src/traits/samplers/geometric/mod.rs, rust/src/traits/samplers/vulnerable_fallbacks/mod.rs
- removes the SampleRademacher trait
- adjusts `SampleDiscreteLaplaceLinear` to avoid some small float inaccuracy at the origin
Before, the algorithm would conservatively work out the probability of not adding noise, and then return the origin without adding noise if a bernoulli sample was positive with this probability. While all probabilities are calculated conservatively, the multiplicative difference between the probability of returning the origin or a neighbor is not exactly the same as the multiplicative differences between other shifts.
The simple solution is to sample geometric noise that starts at zero, and to reject the sample if the sign is negative and offset is zero.
=> switch to rejection sampling in `SampleDiscreteLaplaceLinear`

python/src/opendp/_data.py, python/src/opendp/mod.py, rust/src/data/bootstrap.json, rust/src/traits/bounded/mod.rs
Closes #522.
This adjusts the FFI for the SMD curve evaluation to introspect `T` from the curve struct itself. No additional FFI helpers added, invoking the map reuses `object_type` on the curve, and then retrieves the atom.
=> fix 32-bit SMD Curve downcast

.github/workflows/latex.yml, rust/src/mod.sty
Closes #510 
Adds three macros:
- `\contrib` adds a red box indicating that the proof is part of contrib
- `\asOfCommit{relative_filepath}{commit_hash}` 
- expands to a github permalink to the file at the specified commit hash
- checks if relative_filepath has been updated since commit_hash. 
- if relative_filepath has not been updated, the hash is equivalent, and it emits an `(up to date)` status 
- if relative_filepath has been updated, its git hash won't match, and the macro expands to `(outdated\footnote{*message with git command to see diffs since proof was written})`
- if shell commands are not enabled (like in overleaf), emits a simpler `(unknown\footnote{*instructions on how to enable})` status
- since the proofs are rendered in CI, proof documents automatically indicate if they …
=> common proof boilerplate

python/src/opendp/combinators.py, python/src/opendp/mod.py, python/test/test_comb.py, rust/src/combinators/bootstrap.json, rust/src/combinators/chain/ffi.rs, rust/src/combinators/chain/mod.rs, rust/src/metrics/mod.rs, rust/src/transformations/mod.rs, rust/src/transformations/postprocess/mod.rs
Closes #498
- Adds `make_chain_tm` and the `Shr` trait impls for `>>` chaining
- the chainer completely ignores the null metrics and null map in the postprocessor
- Adds `make_postprocess` that takes an input domain, output domain, and function
- the constructor builds a transformation with null metrics and a null map
=> `make_chain_tm` postprocess combinator

python/src/opendp/mod.py, rust/src/transformations/lipschitz_mul/mod.rs
Closes #581 
Also broadens the error exclusion on `__del__`, as more error types as the interpreter is closing down were not being caught.
=> `make_lipschitz_float_mul` clamp fix

rust/src/lib.sty, rust/src/transformations/count/make_count.tex, rust/src/transformations/count/mod.rs
Moving the proof for the count transformation from last summer's OpenDP Whitepapers repository (https://github.com/opendp/whitepapers/tree/make_count). The TeX file is the same one.
Port of the whitepapers repository PR: https://github.com/opendp/whitepapers/pull/3
=> Port of make_count proof

rust/Cargo.toml, rust/opendp_derive/Cargo.toml, tools/publish_tool.py, tools/release_tool.py
Because we need to munge the version to publish the dependency crates, we ran into an issue with cargo complaining about a dirty repo: https://github.com/opendp/opendp/actions/runs/3325358361/jobs/5497961034
We could use the --allow-dirty flag, but that feels a little dicey.
Instead, this change moves the munging from `publish_tool.py` to `release_tool.py`, which is already dealing with git changes on the release branch.
Side note: We could've tested this locally outside GitHub, and avoided a lot of hassle, if not for the fact that you can't use --dry-run with workspaces. Possible solution here: https://github.com/rust-lang/cargo/issues/1169#issuecomment-1254260875
=> Do crate version munging in release_tool, so changes can be committed.

docs/source/developer/development-environment.rst, docs/source/user/constructors/combinators.rst, python/src/opendp/_convert.py, python/src/opendp/_data.py, python/src/opendp/accuracy.py, python/src/opendp/combinators.py, python/src/opendp/core.py, python/src/opendp/measurements.py, python/src/opendp/mod.py, python/src/opendp/transformations.py, python/src/opendp/typing.py, python/test/test_user_transform.py, rust/build/derive.rs, rust/opendp_tooling/src/bootstrap/arguments.rs, rust/opendp_tooling/src/bootstrap/mod.rs, rust/opendp_tooling/src/bootstrap/signature.rs, rust/opendp_tooling/src/codegen/python.rs, rust/opendp_tooling/src/codegen/python_typemap.json, rust/opendp_tooling/src/lib.rs, rust/src/combinators/amplify/ffi.rs, rust/src/combinators/chain/ffi.rs, rust/src/combinators/compose/ffi.rs, rust/src/combinators/fix_delta/ffi.rs, rust/src/combinators/measure_cast/zCDP_to_approxDP/ffi.rs, rust/src/combinators/mod.rs, rust/src/combinators/user_defined/ffi.rs, rust/src/combinators/user_defined/mod.rs, rust/src/core/ffi.rs, rust/src/data/ffi.rs, rust/src/measures/mod.rs
Closes #44 
Closes #603 
Allows users to write custom transformations, measurements and postprocessors from Python code:
```python
enable_features("contrib", "honest-but-curious")
def make_duplicate(multiplicity):
"""An example user-defined transformation from Python"""
def function(arg):
return [elem + 1 for elem in arg] * multiplicity
def stability_map(d_in):
return d_in * multiplicity
return make_default_transformation(
function,
stability_map,
DI=VectorDomain[AllDomain[i32]],
DO=VectorDomain[AllDomain[i32]],
MI=SymmetricDistance,
MO=SymmetricDistance,
)
trans = (
make_cast_default(TIA=str, TOA=int)
>> make_duplicate(2)
>> make_clamp((1, 2))
>> make_bounded_sum((1, 2))
>> make_base_discrete_laplace(1.0)
)
print(trans(["0", "1", "2", "3"]))
print(trans.map(1))
```
=> support user-supplied callbacks in client code

rust/src/combinators/measure_cast/zCDP_to_approxDP/cks20.rs, rust/src/combinators/measure_cast/zCDP_to_approxDP/mod.rs
Closes #621 
This PR also rejects zero delta, and removes an unnecessary check.
=> clamp negative epsilon in `make_zcdp_to_approxdp`

rust/Cargo.toml, rust/opendp_derive/Cargo.toml, rust/src/combinators/mod.rs, rust/src/domains/mod.rs, rust/src/lib.rs, tools/release_tool.py
Fixes #615
This tweaks a few things so you can run `cargo build` and `cargo test` with the default features, and things will work OK.
* Adds a few '#[cfg(feature="ffi")]'
* Changes a few imports
* Removes versions from local crate dependencies
* Adjusts `release_tool.py` to add local versions, so crate builds continue to work
=> Clean up default builds

python/src/opendp/_lib.py, python/src/opendp/mod.py, rust/Cargo.toml, rust/src/combinators/measure_cast/zCDP_to_approxDP/cdp_epsilon.rs, rust/src/core/ffi.rs, rust/src/domains/ffi.rs, rust/src/error.rs, rust/src/ffi/dispatch.rs, rust/src/transformations/cast/ffi.rs, rust/src/transformations/manipulation/mod.rs
Closes #670 
RelationDebug doesn't have significant performance issues, resolving backtraces does. This PR changes the default behavior to only resolve backtraces in `test` mode, not debug mode.
- remove backtrace crate in favor of Rust 1.65's stabilized std backtrace
- disable backtraces via an environment variable when conducting binary searches 
- avoids a performance cliff when calling the ffi for `atom_domain`, as the dispatch used to rely on error handling
- added a trait that makes it possible to return `None` from `dispatch!`
- avoids a performance cliff when calling `cdp_epsilon` when `rho` is infinity (scale is zero). Instead of overflowing and resolving a backtrace, the function now simply returns `epsilon = infinity`
=> optimize backtrace handling

python/src/opendp/_lib.py
Fixes #717.
* Tweak get_opendp_version to handle uninstalled packages and Python quirks
Putting this in will let us run the documentation CI for release testing.
=> Handle uninstalled package in get_opendp_version

rust/src/domains/ffi.rs, rust/src/measures/ffi.rs, rust/src/metrics/ffi.rs
Closes #727 
Fixes a bug in #729 that wasn't caught by testing, likely because `__del__` isn't guaranteed to run.
=> free supporting elements (fix symbols)

docs/source/user/combinators.rst, docs/source/user/combinators/compositors.ipynb, python/src/opendp/mod.py, python/src/opendp/typing.py, python/test/test_interactive.py, rust/src/combinators/composition/sequential/ffi.rs, rust/src/data/ffi.rs, rust/src/ffi/util.rs, rust/src/measures/ffi.rs
Closes #732
Also adds a data loader for `Vec<(f32, f32)>`, `Vec<(f64, f64)>`.
This is so that the sequential compositor can take a vec of d_mids when working in approximate-DP.
=> composition notebook

.github/workflows/docs.yml, .github/workflows/release.yml, CHANGELOG.md, docs/Makefile, rust/src/combinators/fix_delta/mod.rs, rust/src/data/ffi.rs, rust/src/metrics/mod.rs, rust/src/traits/mod.rs, rust/src/traits/operations/mod.rs, rust/src/transformations/count/mod.rs, rust/src/transformations/impute/mod.rs, tools/publish_tool.py, tools/release_tool.py, tools/test.py
Fixes #709:
* Update CHANGELOG.md
* Fix some problems with default build
* Clean up some nits in rustdoc
* Add option to `release_tool.py` to use a different release branch prefix
* Add ability to run `release.yml` manually on a different branch
* Add ability to run `docs.yml` manually to fill in missing proofs
* Update pre/post-flight test script to use `SymmetricDistance`
* Point dry run at TestPyPI (`twine` has no `--dry-run` option)
* Add `--features untrusted,ffi` to `make doctest-rust` target
=> 0.7.0 release prep

python/src/opendp/transformations.py, rust/src/transformations/cast/mod.rs, rust/src/transformations/clamp/mod.rs, rust/src/transformations/impute/mod.rs, rust/src/transformations/index/mod.rs, rust/src/transformations/manipulation/mod.rs
Closes #724 
Reorders arguments to be consistent with the partials API. 
Generalizes the constructor to be able to support row-by-row maps between different database domains.
Tweaked the function contract to prepare for the privacy proof.
=> dom/met signature: `make_row_by_row`

.github/workflows/release.yml, .github/workflows/smoke-test.yml, README.md, docs/source/contributor/development-environment.rst, docs/source/user/installation.rst, docs/source/user/programming-framework/supporting-elements.rst, python/setup.cfg, python/src/opendp/domains.py, python/src/opendp/mod.py, python/src/opendp/typing.py, python/test/test_space_of.py, python/test/test_typing.py, rust/src/domains/ffi.rs, rust/src/ffi/util.rs
Closes #748
Adds a convenience constructor for building metric spaces in Python.
```python
import opendp.prelude as dp
(dp.vector_domain(dp.atom_domain(T=dp.i32)), dp.symmetric_distance())
dp.space_of(list[int])
dp.space_of(list[int]) >> dp.t.partial_clamp((0, 10))
```
As a whole, the library is moving towards specifying the input domain and input metric up-front. This helper gives a simpler alternative to learning a set of domain/metric builder APIs.
This PR also addresses some nits:
* FFI for `map_domain` (which we had missed before)
* updates typing code to work with [Python 3.9 type annotations](https://docs.python.org/3.9/whatsnew/3.9.html#type-hinting-generics-in-standard-collections) (like `list[int]`)
* registers DiscreteDomain among the FFI types (which we had missed before)
* …
=> Python convenience constructor for metric spaces

python/test/test_meas.py, rust/src/combinators/measure_cast/zCDP_to_approxDP/cdp_epsilon.rs, rust/src/core/ffi.rs, rust/src/core/mod.rs, rust/src/error.rs, rust/src/measurements/gaussian/continuous/mod.rs, rust/src/measurements/gaussian/discrete/mod.rs, rust/src/measurements/laplace/continuous/mod.rs, rust/src/measurements/ptr/mod.rs, rust/src/traits/mod.rs
Closes #844 (infinite loop in zCDP_to_approxDP when δ=0)
Closes #656 (privacy maps return zero when d_in=0)
Closes #654 (new_from_constant enforces c>= 0)
=> polish edge-cases in maps

.github/workflows/release.yml, python/src/opendp/_lib.py, tools/python_build.sh, tools/rust_build.sh
Fixes #817.
* Refactor `release.yml` to include target `aarch64-unknown-linux-gnu`
* The main grief was getting `gmp` to cross compile to aarch64 from x86_64.
The configure script just wouldn't work with the toolchain in the standard `manylinux_2014` images,
but `messense/manylinux2014-cross` seems to have a better setup.
* Because linux doesn't have fat binaries, we need to have separate `libopendp-XXX.so` files with tagged names
* Also did some cleanup of action versions
* Tweak rust_build.sh and python_build.sh
* Add logic to _lib.py to load arch-specific libraries
=> Add aarch64-unknown-linux-gnu target

.binder/requirements.txt, CHANGELOG.md, VERSION, python/setup.cfg, python/src/opendp/_lib.py, rust/Cargo.toml, rust/opendp_derive/Cargo.toml, rust/opendp_tooling/Cargo.toml, rust/opendp_tooling/src/bootstrap/docstring.rs, rust/opendp_tooling/src/proven/filesystem.rs, rust/src/ffi/dispatch.rs, rust/src/lib.sty, tools/assert_version.py, tools/requirements-assert_version.txt, tools/utils.py
Phase 1 of nightly builds. This part is limited to updating the version references in various files to match the new scheme, plus tweaking the codegen that consumes them.
* Adopt 3 release channels, with corresponding branches (takes full effect in #880)
* `nightly` pulls from `main` every night (if there are changes)
* `beta` pulls from `nightly` every 3 months, ~1 week before release
* `stable` pulls from `beta` every 3 months
* switch from null version `0.0.0+development` to correct version on each channel
* `main`: `X.Y.Z-dev`
* `nightly`: `X.Y.Z-nightly.YYYYMMDD.N`
* `beta`: `X.Y.Z-beta.YYYYMMDD.N`
* `stable`: `X.Y.Z`
* The various `Cargo.toml` files were updated so that internal dependencies have good versions (which get updated by `channel_tool.py` as necessary).
* …
=> Nightly Build Phase 1: Migrate to new version scheme

.github/workflows/release.yml
Fixes #714.
From the nightly run last night, everything worked until the post-release sanity test (failure: https://github.com/opendp/opendp/actions/runs/5676312359/job/15383615116). There was a hard-coded reference to `testpypi` left over from testing. 
I tried to clean up the dry-run logic in `release.yml`, by having a single environment variable, but GH actions don't allow you to reference top-level environment variables in jobs. (See https://github.com/orgs/community/discussions/26529 for discussion and a clunky workaround.) So the `inputs.dry_run || inputs.fake` logic remains inline.
=> Use correct repo for sanity-test

rust/src/domains/mod.rs, rust/src/interactive/mod.rs, rust/src/measurements/alp/mod.rs, rust/src/traits/cast/mod.rs, rust/src/traits/mod.rs, rust/src/transformations/count/ffi.rs, rust/src/transformations/count/mod.rs
Closes #755
The constructors are now named:
* `make_alp_state_with_hashers`
* `make_alp_state`
* `make_alp_queryable`
Just like before, each constructor calls the previous one. The `make_alp_queryable` constructor is the one meant to be used from Python (implemented in #747)
Generics have been renamed:
* `C` -> `CI` for "input count"
* `T` -> `CO` for "output count"
Arguments have been renamed/reordered to be more consistent with other constructors, to highlight the repetition in limit/upper bound arguments, and to make optional arguments trailing. 
These constructors now also follow the (new) library convention of passing the input domain and input metric in as the first two arguments of the constructor, and read what they can from the input.
What should be the only substantive change to …
=> update sparse histogram api

.binder/requirements.txt, docs/source/conf.py, tools/channel_tool.py
Fixes #909.
* Make `channel_tool.py` update version dependencies version for `opendp_tooling`
* Have `nbsphinx_prolog` Jinja magic use `env.config.release` for constructing binder links
* Add `requirements_notebooks.txt` to binder requirements
=> Fix 0.8 release issues

tools/assert_version.py
Fixes #919.
Guard against None when checking for dev version.
=> Handle stable version

rust/src/metrics/mod.rs, rust/src/transformations/cast_metric/mod.rs, rust/src/transformations/cast_metric/traits.rs, rust/src/transformations/manipulation/mod.rs, rust/src/transformations/mod.rs, rust/src/transformations/quantile_score_candidates/mod.rs
Closes #325 
* adds a new scorer transformation `make_quantile_score_candidates`
* the constructor accepts a vector of quantile candidates
* the transformation transforms a dataset to a vector of scores, one per candidate
* adds a new metric `LInfDiffDistance<U>` for representing the sensitivity of score vectors
=> add `make_quantile_score_candidates`

rust/src/measurements/discrete_exponential/mod.rs, rust/src/measurements/mod.rs, rust/src/traits/samplers/discretize/mod.rs, rust/src/traits/samplers/mod.rs, rust/src/traits/samplers/psrn/mod.rs, rust/src/traits/samplers/vulnerable_fallbacks/mod.rs, rust/src/transformations/quantile_score_candidates/mod.rs
This PR implements a floating-point-safe exponential mechanism via partially sampled random numbers (PSRN). 
This implementation exploits the nice property of the Gumbel noisy-max algorithm wherein each Gumbel variate only needs to be known with sufficient precision to guarantee that no other Gumbel variate can be greater than the best-scoring Gumbel variate (or top k).
The sampling starts with a uniform PSRN, initialized to the interval [0, 1]. The next bit of the uniform random number is acquired by randomly halving the interval. The lower and upper edge of the interval can be retrieved at any given time.
There is similarly a Gumbel(μ, 1) PSRN supported on the reals with rational μ. It contains a uniform PSRN, an inverse transform precision u32, and a shift Rational. In each refinement …
=> add `make_base_discrete_exponential`

python/src/opendp/transformations.py, rust/src/trans/manipulation/make_is_equal.tex
Moving the proof for the is_equal transformation from last summer's OpenDP Whitepapers repository (https://github.com/opendp/whitepapers/tree/is_equal). The TeX file is the same one.
Ported from the whitepapers repository PR: https://github.com/opendp/whitepapers/pull/2
=> `make_is_equal` proof

rust/src/ffi/any.rs, rust/src/ffi/util.rs
Before/after:
* `Failed downcast_ref of AnyBox to polars_lazy::frame::LazyFrame`
* `Expected data of type LazyFrame. Got Vec<AnyObject>`
=> user-friendly downcast-ref error message

python/src/opendp/context.py
- Towards #997
Rather than making a PR against `main` I've created a new branch, https://github.com/opendp/opendp/tree/997-concrete-query-methods-IN-PROGRESS, with the idea that smaller PRs could be reviewed and merged into it, rather than leaving `main` half-baked. Is this approach ok?
Questions on this bit:
- Since the Context API is designed to be used end-to-end, I'm not sure that there is a good minimal example. Is a long example like this too much clutter?
- Are there other things we do definitely want in the docs? Exceptions?
- In the draft, you had proposed `Query.extend`, which I'm interpreting as a new static method. It looks like `new_with` already does what we need: Ok to just use that?
- Are you imagining that the Laplace helper will do the binary search to determine the …
=> 997 concrete mean and laplace on query

.github/workflows/smoke-test.yml, python/.mypy.ini, python/requirements-dev.txt
- Fix #1023
- Builds on #1029
Even with the 13 error codes we ignore here, this is protecting us against a number of other possible errors: I think there are 47 mypy error codes total:
```
wget https://raw.githubusercontent.com/python/mypy/master/docs/source/error_code_list.rst
grep '.. _code-' error_code_list.rst | perl -pne 's/.*_code-//; s/://' | sort | wc -l
47
```
If this much is good, can file a follow-up issue to address the errors in the ignore list: They might be the result of misusing the tool and not real errors at all, for all I know.
=> Add mypy and check python type annotations

docs/source/conf.py
- Adds to #1055 (Thought this was in there, but must have reverted it by mistake.)
- twitter and github can just be on the resources page: They don't need this real estate.
=> Remove twitter and discussion from banner

.github/workflows/smoke-test.yml, docs/linkchecker.cfg
- Builds on #1095
With more tooling in place, we probably want to pull some of it into separate jobs. Not because we're expecting to save any CI time from parallelizing -- these checks run fast -- but to save developer time: It's annoying to fix an issue in linting ... and then CI tells you there's a problem with typing ... and then there's a problem with tests.
It does add a lot of lines to the YAML.
- Making more artifacts seems like overkill
- Most of the steps could be reduced to a single line, at some cost to readability
- use YAML shortcuts to minimize copy and paste.
Filing as draft for now.
=> pull out linting and typing as separate jobs

.github/workflows/prepare.yml, .github/workflows/publish.yml, .github/workflows/sanity-test.yml, docs/linkchecker.cfg, tools/build_tool.py, tools/channel_tool.py, tools/publish_tool.py
- Builds on #1105
- More transparent
- Less fragile
- Less code, when we let the `dest` be implicit.
=> Use longer param names for flags

.github/workflows/prepare.yml, .github/workflows/release.yml
- Fix #1089
In release.yaml, `dry_run` is never referenced alone. I'll make a branch from this and see if I can make a top-level variable to capture `inputs.dry_run || inputs.fake`, rather than repeating it across the file.
=> pass dry_run to prepare.yml

.github/workflows/README.md
- Refinement of #1082
Just link directly to the workflow on github, instead of explaining how to navigate the UI
=> Link directly to release.yml

docs/Makefile, docs/requirements.txt, docs/source/conf.py
- Fix #990
After updating dependencies and rebuilding, the search issue is resolved. There are several issues in their repo related to search UI. If I leave the search in the sidebar, we still have the same problem as before, even with the upgrade.
=> Upgrade pydata-sphinx-theme; use default search UI

.github/workflows/publish.yml, .github/workflows/release.yml, tools/publish_tool.py
- Toward #1130 
It looks like I had run `release.yml` on the branch with the change... but it didn't _really_ run: https://github.com/opendp/opendp/actions/runs/7197498991 -- It just ran `debug` and exited in 10s. Lesson: green checkmark isn't enough -- confirm that it is actually doing the right thing.
Update: The workflow run is still failing on this branch: The new `--counter` flag is not being recognized… Looking up to the top:
```
publish-python:
...
steps:
- name: Checkout repository
uses: actions/checkout@v3
with:
ref: ${{ inputs.channel }}
```
So it’s running the workflow from `nightly`, not from this branch.
Normally, `prepare.yml` would have updated nightly with the changes in this PR… but since it’s a dry-run, it doesn’t.
Not sure how best to move this forward: Maybe run it …
=> get rid of `env` that was causing error

.github/workflows/build.yml, .github/workflows/latex-release.yml, .github/workflows/prepare.yml, .github/workflows/publish.yml, .github/workflows/release.yml, .github/workflows/sanity-test.yml, tools/channel_tool.py, tools/publish_tool.py
Adds a new channel `experimental` that can be used to cut one-off releases to test-pypi from arbitrary branches.
Closes #1142
=> experimental channel for one-off releases

python/src/opendp/context.py, python/src/opendp/extrinsics/__init__.py, python/src/opendp/mod.py, python/src/opendp/typing.py
- Fix #1129
- and add more docs on `mod`
I would like to add more links in both directions, but there are downsides:
- The relative links won't work if these docs are used by an IDE.
- They will need to be adjusted following doc reorg. (linkchecking will catch problems, it will just be a little chore.)
=> Short summaries of python modules

docs/source/user/combinators.rst, python/src/opendp/mod.py
- Prompted by #1001
- and [Evaluating the Usability of Differential Privacy Tools with Data Practitioners](https://arxiv.org/abs/2309.13506)
Proposal: New users have trouble getting OpenDP to work for them. One issue is the leakage of Rust details into the Python environment: A rust stack trace isn't something a python enduser can do anything with. I'd propose that we hide the rust details by default, and developers can turn them on, if that's needed.
=> Add a new feature that controls whether rust stack traces are shown

rust/src/ffi/mod.rs, rust/src/lib.rs
- Fix #1149
- Note that the FFI docs could use some work: #1148 -- That page was rendered as part of the documentation before, but as part of the public API cleaning it up may be a higher priority.
- (Michael explains that we are rendering all docs, even for code that is not public, so proofs can be linked.)
- Should anything else change, assuming this is the right direction?
=> Make ffi public

python/src/opendp/mod.py, python/test/test_core.py
While it is neat for Mypy to be able to infer return types of binary search based on types of bounds/predicate, 
oftentimes these types are not given or unknown.
This causes inconvenient warnings from Mypy that the type parameter is unknown.
Closes #1161
=> loosen type requirements on binary searches

python/src/opendp/_convert.py, python/src/opendp/_lib.py, python/src/opendp/core.py, python/src/opendp/measurements.py, python/src/opendp/mod.py, python/src/opendp/prelude.py, python/test/test_interactive.py, python/test/test_user_transform.py, rust/src/core/ffi.rs, rust/src/measurements/make_user_measurement/mod.rs
Closes #1146
* the second argument on queryable transition functions (generally unused internal query indicator) is now optional
* rename `new_user_queryable` -> `new_queryable` for consistency with `new_function`. It's not a privacy structure
* try/catch object_free, as it failed to call during interpreter shutdown like the other free functions do
* specify default parameters of "ExtrinsicObject" for measurement's TO, and queryables' Q and A
* raw functions can now be chained as postprocessors onto measurements, without wrapping in `new_function`
=> UDFs default to ExtrinsicObject and QOL

.github/workflows/smoke-test.yml
- Fix #1154
- Remove the docstrings that shouldn't have been committed in the first place
- ... and comment out the test that checks the docstrings.
The test failure on the second commit below shows what it looks like when there are changes to the generated files.
This seems like it might make things less error-prove... but I've been wrong before. It might also cause merge conflicts with work you already have in progress. We might kill this PR, and apply the idea in a different branch, or just wait until the release is out.
A totally different approach would be to git-ignore all the generated files. That could work, but it feels like a bigger change from what we have now, and we'd also have to keep the ignore list up to date, or distinguish the generated files by name or path.
=> Confirm that generated python is in sync

R/opendp/R/measurements.R, python/src/opendp/measurements.py, rust/src/measurements/gumbel_max/mod.rs
This flag never needed to be set. The implementation has always been floating-point-safe.
=> remove floating-point flag from RNM Gumbel

.flake8, rust/src/measurements/gumbel_max/pseudocode/make_report_noisy_max_gumbel.py, rust/src/traits/samplers/uniform/pseudocode/sample_uniform_int_below_native.py, rust/src/transformations/quantile_score_candidates/pseudocode/compute_score.py
- Fix #1197
There are actually only a couple of errors for our current flake8 config, and they all seem like typos we would like to catch.
Looking at this, I am also reminded that many of the flake8 checks are still turned off, including ones that we would like to run on pseudo code:
```
def compute_score(
x: List[TIA], 
candidates: List[TIA], 
alpha_numer: usize,
alpha_denom: usize,
size_limit: usize
) -> List[usize]:
...
alpha_den * min(lt, size_limit),
alpha_num * min(len(x) - eq, size_limit))
```
Note `alpha_numer` vs `alpha_num` -- This is something we'd like to catch in the production code too! I think that removing this from the ignore list would surface these problems:
```
F821,
```
- See #1069
=> fix typos and run flake8 on pseudocode

docs/source/contributor/development-environment.rst
- Fix #1223 (Actually, move every language install down to the appropriate section.)
- Correct envvar
- Add missing double backticks
- Second level headers
=> Update and fix typos on dev instructions

R/opendp/R/accuracy.R, R/opendp/R/combinators.R, R/opendp/R/core.R, R/opendp/R/data.R, R/opendp/R/domains.R, R/opendp/R/measurements.R, R/opendp/R/measures.R, R/opendp/R/metrics.R, R/opendp/R/transformations.R, R/opendp/_pkgdown.yml, rust/opendp_tooling/src/codegen/r/r.rs
- Towards #1244... but keep it open for now.
Tweaked the Rust codegen to include `@concept` in the generated docstrings. With this, R pkgdown can be configured to include headings.
If this much is useful, there are a couple of follow-ups which could be filed.
- Generate `_pkgdown.yml` in Rust, so the list stays consistent.
- Split up the `Other` catch all by adding `@concept` on the non-generated files.
=> Subheadings in R docs

.github/workflows/README.md, .github/workflows/docs.yml
make the dependency on r-docs explicit, at the cost of slowing down the docs build
- Possible fix #1242, but there are other approaches, including doing nothing.
=> Make docs dependency on r-docs explicit

.github/workflows/smoke-test.yml
- Elevate check warnings to errors, just to be safe.
- Does not address #1251, sadly: `devtools::document` does not support `error_on` and I haven't found an alternative.
=> Error on warning from devtools::check

.github/workflows/publish.yml
If we want to treat `r-universe-dev` like `testpypi` then this seems appropriate... but if we want to make sure that nothing gets pushed to any branch on github from a dry-run, should try something different.
- fix #1266
=> Now if "stable" and "dry-run" are selected, will append "-dev"

rust/src/measurements/alp/mod.rs
I think the map on this is backwards, could you check @ChristianLebeda? Thanks. This is a sign we need better proof coverage!
I also adjusted the code to not panic when scale is zero.
=> Avoid panic in ALP histogram

.gitignore, R/opendp/README.md, tools/r_stage.sh
Towards #1244
Just repeating the top-level README doesn't tell R users much, but I think there are a few things we could point out to them before letting them loose on the generated docs.
We are a little constrained: It should work both as a readme for this directory, and as a source for generated docs. Considered relative link to the API reference... but that wouldn't work when the README is viewed in github.
=> R doc README

.github/workflows/build.yml, tools/build_tool.py
- Fix #1172
There is also a 2_28 out, but maybe be safe? I've confirmed on quay and dockerhub that these images exist. 
[Dry-run of build running now.](https://github.com/opendp/opendp/actions/runs/7935903813)
Also: It doesn't look like `build_tool.py` is referenced anywhere. I've done some linting on it recently, but before that the last commit was
```
commit ae35ac4e7457da687611117c98f279da37a9c3a2
Author: Andrew Vyrros <6577271+andrewvyrros@users.noreply.github.com>
Date:   Tue Oct 25 14:06:42 2022 -0700
* Try manylinux2014_x86_64 (#592)
* Switch args to toml.dump()
```
Avoiding vendor lock-in is a good goal, but I don't think we've maintained this, and it may just cause confusion now. Ok to delete?
=> manylinux2014 -> manylinux_2_24

python/src/opendp/context.py, python/test/test_comb.py
I'm not sure of the metric in `test_comb.py`: @Shoeboxam, can you make a suggestion there?
My sense is that `context` might go away, to be replaced by Polars, so we don't need to invest more time there? Though if it is staying, the test coverage could be improved.
- Fix #1264
- Unblock #1263
=> Fix masked mypy errors

python/src/opendp/_data.py, python/src/opendp/_lib.py, python/src/opendp/accuracy.py, python/src/opendp/combinators.py, python/src/opendp/core.py, python/src/opendp/domains.py, python/src/opendp/measurements.py, python/src/opendp/measures.py, python/src/opendp/metrics.py, python/src/opendp/transformations.py, rust/opendp_tooling/src/codegen/python.rs
- Remove one line from Rust code and regenerate Python
- Since it's now unused, remove function
- Fix #1145
(If you're looking at that issue, note that it started from a misunderstanding on my part: it's `@versioned` rather than `@proven` which is vestigial.)
=> Remove `@versioned` from generated code

.flake8, python/src/opendp/_convert.py, python/test/test_typing.py
- Fix #1281
- Drop special handing for python < 3.8 -- If we want to offer some support for versions < 3.8, we should add it to the test matrix. 
- Catch `Exception` instead of implicit `BaseException` -- The tests don't currently exercise this line, so I'm not confident about the change. Since any exception here would be surprising, would we like to log it?
=> no more bare excepts

R/opendp/R/combinators.R, R/opendp/R/measurements.R, R/opendp/R/mod.R, R/opendp/R/transformations.R, R/opendp/R/typing.R, R/opendp/_pkgdown.yml, rust/opendp_tooling/src/codegen/r/r.rs
Some manual (mod and typing), some generated (the `then` functions).
- fix #1256
("Concepts" are what provide grouping in R docs.)
=> A concept on every R function

python/src/opendp/core.py, python/src/opendp/mod.py, python/test/test_user_transform.py
- Fix #1190
- Fix #1339
- Test the failing behavior
- Update the typing
- Remove coverage skip that isn't needed.
I think this does what we need, but I could be missing something.
=> Runtime error if non-function is passed to `new_function`

rust/opendp_tooling/src/codegen/mod.rs, rust/opendp_tooling/src/codegen/python.rs, rust/opendp_tooling/src/codegen/r/c.rs, rust/opendp_tooling/src/codegen/r/r.rs, rust/src/combinators/mod.rs
Prereq for 
- #1364 / #1342
steps:
- added param to function
- search and replace usages
- cargo fmt, which introduces most of the changes, considered line by line.
Thought about introducing wrapper functions `indent_2` and `indent_4`, but this seems simpler, but no strong feelings.
Implicitly tested by the check for local changes to the generated code after the cargo build.
=> Add `number_of_spaces` param to `indent`

.github/workflows/build.yml, .github/workflows/release.yml, tools/update_notes.R
- Fix #1349
envvar usage prevented CI from starting. See https://github.com/opendp/opendp/actions/runs/8135561781/workflow. The problem is really with `release.yml`, not `nightly.yml`. Simplify, by just repeating `inputs.dry_run || inputs.fake`. In some cases, only check `fake`, because not every `dry_run` is also `fake`
- Does the usage of `dry_run` vs `fake` now represent the behavior we want?
- Do we really need to support `fake`? I guess the idea is to speed up the build when we're exercising other parts of this... but I think it has been confusing.
- If we do want to support it, would it be more clear to have a select with three options, rather than than two checkboxes, one of which implies the other?
Need to manually run nightly on this branch and confirm that it works.
=> Fix nightly

rust/opendp_tooling/src/codegen/mod.rs, rust/src/core/mod.rs
- Fix #1374
These don't seem to be necessary.
=> Remove dead_code markers that do not cause warnings in IDE

python/src/opendp/context.py, python/src/opendp/mod.py, python/src/opendp/typing.py
- Fix #1390
- Will cause a small conflict with #1386, but didn't want to expand the scope of that PR unnecessarily.
Am I correct in thinking that `loss_of` is the most idiomatic way to construct a `Measure`? Change the wording here if not.
=> Measure `__str__` -> `__repr__`

tools/python_build.sh
- hopefully fix #1413
- follow-up to #1415
- related to #1426 -- with each script having its own requirements, it's easy to get confused and not add dependencies where needed. Since debugging the CI is annoying, it would be good to make this simpler and more robust.
Will file as draft and start a dry-run: https://github.com/opendp/opendp/actions/runs/8424738627
=> Add setuptools, fix nightly?

docs/Makefile
With this change, the ToC looks like:
I think it's an improvement, but it is subjective.
- Fix #1294
=> API ToC just down to modules

.github/workflows/README.md
- Follow-up to #1414 -> #1434
Trying to make this page more of a dashboard where any important build problem will show up.
Note that because of our naming convention for the nightlies (adding a suffix to the previous release, rather than a suffix on the upcoming release), docs.rs still reports the build as broken -- or at least I think that's what's going on.
=> Add a badge for docs.rs

python/test/test_context_usability.py
I tripped several times coming up with the simple `Context` example in #1458, and wanted to capture the errors a typical user might hit. I don't know enough about the project direction to immediately file new issues for each of these: Maybe work that's in progress will take care of them?
Going forward, when we ourselves or outside users hit an error that isn't helpful, we might consider adding a test here.
- Towards #1422 
- With #1456 merged, and strict turned on, if one of these stops erroring, it will fail the test.
=> xfail usability tests

docs/source/api/user-guide/combinators/index.rst, docs/source/api/user-guide/context/index.rst, docs/source/api/user-guide/index.rst, docs/source/api/user-guide/measurements/index.rst, docs/source/api/user-guide/programming-framework/core-structures.rst, docs/source/api/user-guide/programming-framework/index.rst, docs/source/api/user-guide/programming-framework/supporting-elements.rst, docs/source/api/user-guide/transformations/index.rst, docs/source/api/user-guide/utilities/accuracy.rst, docs/source/api/user-guide/utilities/typing.rst, docs/source/conf.py, python/src/opendp/accuracy.py, python/src/opendp/combinators.py, python/src/opendp/context.py, python/src/opendp/core.py, python/src/opendp/domains.py, python/src/opendp/measurements.py, python/src/opendp/measures.py, python/src/opendp/metrics.py, python/src/opendp/transformations.py, python/src/opendp/typing.py, rust/opendp_tooling/src/codegen/python.rs
- Fix #1388 (Replaces #1445)
- Fix #973 (could do more, but enough for now)
- Link from every module to a corresponding section of the user guide
- Link from many sections of the user guide to corresponding modules
- And special boilerplate for our three special modules.
- Make the anchors more consistent.
=> links between user guide and api reference

.github/workflows/docs.yml, docs/tools/rst-to-nb.py
I didn't file a new issue for currently nightly failure.
Haven't dug into the git history to understand what went wrong, but the fix seems simple. Confirmed that with this commit every `actions/upload-artifact` is v4.
=> r-docs artifact: We were uploading r-docs with v2, downloading with v4

R/opendp/src/opendp.h, python/src/opendp/_convert.py, python/src/opendp/domains.py, python/src/opendp/typing.py, python/test/test_convert.py, python/test/test_polars.py, rust/opendp_tooling/src/bootstrap/signature.rs, rust/opendp_tooling/src/codegen/python_typemap.json, rust/opendp_tooling/src/codegen/r/mod.rs, rust/src/data/ffi.rs, rust/src/domains/polars/frame/ffi.rs, rust/src/domains/polars/frame/mod.rs
=> Polars: `lazyframe_domain` ffi

R/opendp/src/convert.c
Close #1535
I wish they would provide more documentation on their APIs. No wonder everyone is calling it wrong!
Fix from Dirk here (thank you):
https://github.com/RcppCore/Rcpp/issues/1287#issue-2011132718
=> resolve R warning when calling Rf_error in C

python/test/test_core.py
- Fix #1560
For the later checks, the date doesn't actually matter, but seems safer just to make this a constant.
=> replace datetime.now() with constant

.github/workflows/smoke-test.yml
If I ever make a mistake and submit my stack twice, the old batch of CI runs don't get canceled, meaning the CI runners are consumed on useless tasks for an extended time.
=> cancel old smoke-test CI runs

.github/workflows/smoke-test.yml
* -3 Don't run rust tests twice (these got re-introduced in the rust-build task from the --all-features pr)
* -12 Don't run the disk cleaner (not actually seeing CI fail now, and it didn't used to take this long. leaving commented)
* -3 Don't vendor dependencies (they're not used by the r tests)
* -5 Don't run rust doctests (just the 31 doctests, many of which are internal, take 5 minutes on their own)
* Perhaps we can move rust doctests out to unit tests in future work
This reduces smoke-test from 31 minutes to 7 minutes.
=> speed up smoke-test

python/src/opendp/_extrinsics/_make_np_eigenvector/__init__.py, python/src/opendp/_lib.py, python/test/extrinsics/test_csprng.py, python/test/extrinsics/test_np_pca.py, python/test/helpers.py, python/test/test_tests.py
- Replace #1433: Just easier to start fresh.
- Extends #1348
- Finally fix #1347
As a TODO notes, it would be cleaner to use a class to hide state rather than module level private variables... but that would also be a bigger change, and I think this is sufficient for now.
With this change, there is only one use of `skipif` and it's not for optional dependencies:
```
@pytest.mark.skipif(sys.version_info < (3, 11), reason='mypy will fail on 3.8')
```
=> randomgen guards, again

.github/workflows/smoke-test.yml, python/setup.cfg, python/src/opendp/_convert.py, python/src/opendp/_lib.py, python/src/opendp/measurements.py
This PR:
- #1576
clobbered the API example from
- #1581 
and caused the tests to fail when merged. 
The longterm fix to avoid this problem is
- #1430 
though I have some ambivalence there.
=> regenerate python to include example

.github/ISSUE_TEMPLATE/new-contribution.md
- Fix #1637
Also, this was a chance to exercise the new 404 page JS-redirect machinery. For both of these, it works: Users are directed from the old URLs to the new.
=> update links to match new docs structure

docs/requirements.in, docs/requirements.txt
- Fix #1517 
Confirmed locally that search now shows snippets. The only other difference I see with this release is the styling of tabs: They seem clunkier to me, but I don't think it's something we should fight.
When there is a final release, we should certainly use it, but I'm not seeing any problems with the RC, and the search snippets are a big win.
Took me longer than I'd like to admit to confirm that it works locally. The upstream fix is a change to the document template (to restore a `role="main"` attribute) so there are a number a cache layers to clear:
- Checkout the branch and `pip install -r requirements.txt`
- Clear the sphinx build cache with `rm -r build/html`
- Because of browser security rules, it doesn't work with just `file:///`: Instead you'll need `python -m …
=> Upgrade pydata theme for search snippets

python/src/opendp/context.py, python/test/test_context_usability.py, python/test/test_space_of.py
- Add some tests where the behavior seems clear enough.
- Where there are still gaps, add an explicit TODO.
- On `context.__call__` suggest deleting unused/untested branch, particularly since it simplifies the typing.
- Add typing, and a couple run-time checks.
There is the risk here of just hardening behavior that isn't what we really want, but I'm hoping that this at least helps to make gaps visible.
=> Improve test coverage in `context.py`

python/src/opendp/_convert.py
- Test coverage ignores are no longer needed
- In some places, mypy isn't smart enough to infer something that we know is true. Adding asserts here will give us an earlier warning if something has gone wrong.
- clean up other typing ignores.
=> Improved test coverage and typing in  _convert.py

python/.pytest.ini, python/src/opendp/_lib.py
- Fix #1619 by removing duplicate code
- Pytest will now treat warnings as errors
- ... which flagged an open filehandle warning, so fix that, too
=> Fix polars override namespace warning

python/test/test_polars.py, rust/src/transformations/make_stable_lazyframe/filter/mod.rs, rust/src/transformations/make_stable_lazyframe/filter/test.rs, rust/src/transformations/make_stable_lazyframe/mod.rs
Closes #899
Example usage.
```python
import opendp.prelude as dp
import polars as pl
def placeholder(schema):
return pl.DataFrame(None, schema, orient="row").lazy()
dp.enable_features("contrib")
lf = pl.LazyFrame(
[
pl.Series("A", [1.0] * 50, dtype=pl.Float64),
pl.Series("B", [1, 2, 3, 4, 5] * 10, dtype=pl.Int32),
pl.Series("C", ["1"] * 49 + [None], dtype=pl.String),
pl.Series("D", [2] * 50, dtype=pl.Int32),
]
)
lf_domain = dp.lazyframe_domain(
[
dp.series_domain("A", dp.atom_domain(T=dp.f64)),
dp.series_domain("B", dp.atom_domain(T=dp.i32)),
dp.series_domain("C", dp.option_domain(dp.atom_domain(T=dp.String))),
dp.series_domain("D", dp.atom_domain(T=dp.i32)),
]
)
lf_domain = dp.with_margin(
lf_domain, by=["C"], public_info="keys", max_partition_length=50
)
proposed_plan = ( …
```
=> Polars: filter

.github/workflows/smoke-test.yml, python/setup.cfg, python/src/opendp/_lib.py, python/src/opendp/mod.py, python/test/test_polars.py, rust/src/data/ffi.rs
- Replaces #1636
Mistakenly added new commits to that branch, and a new PR seems like the least confusing way to go forward.
Last comment from that PR:
> For users, this doesn't enforce strict version matches... but if there is an error, and there is a mismatch, it includes more information, saying exactly what version it saw and what version it expected. With the current state, I think it could be frustrating to be a downstream user, particularly if some other library includes opendp as a dependency, but forgot to reference our `[polars]` extra. The user is going to have some trouble figuring out what version _would_ fix the error.
> 
> ... it's also possible that version mismatch is not the problem... I think I hit this at one point, though I don't remember the details, and I may be …
=> Python polars version: Extra info on error if mismatch with Rust

.github/workflows/smoke-test.yml, python/setup.cfg, python/src/opendp/_lib.py, python/src/opendp/mod.py, python/test/test_polars.py, rust/src/data/ffi/mod.rs
- Fix #1631 
- Redo of #1663, which I merged onto the wrong branch.
- (And that PR replaced #1636.)
- This just rebases it onto main.
> For users, this doesn't enforce strict version matches... but if there is an error, and there is a mismatch, it includes more information, saying exactly what version it saw and what version it expected. With the current state, I think it could be frustrating to be a downstream user, particularly if some other library includes opendp as a dependency, but forgot to reference our `[polars]` extra. The user is going to have some trouble figuring out what version _would_ fix the error.
> 
> ... it's also possible that version mismatch is not the problem... I think I hit this at one point, though I don't remember the details, and I may be misremembering. But …
=> Add more informative error message if Python and Rust polars versions don't match

python/src/opendp/typing.py, python/test/test_typing.py
- `infer` has a lot of what seems like odd behavior to me: add comments -- Before merging, decide on next steps and file issues if needed.
- Remove special handling for Measurement and Transformation: canonical examples like `make_gaussian` fall through to the callable check, so these don't seem to be doing what we'd want.
- exercise `set_default_float_type`
- Remove special warning for `AllDomain`: It was deprecated in v0.7, so seems safe to remove now.
=> Improve test coverage in `typing.py`

python/src/opendp/typing.py, python/test/test_typing.py
Prompted by https://github.com/opendp/opendp/pull/1652/files#r1642781252 
I don't understand the data load process in detail, but at least on the evidence of our tests it doesn't seem to be needed now.
=> chore: remove `UnknownType` and instead immediately raise exception

docs/source/api/user-guide/combinators/compositors.rst
- Fix #1802
Is the right style just the numbers?
=> Remove epsilon/delta units in docs

.github/workflows/README.md, .github/workflows/release.yml, .github/workflows/update-bindings.yml
Closes #1829
Adds a step in the release workflow that commits the generated code to the channel branch. As a byproduct, this also fixes how links to proofs in releases still point to nightly.
See CI run showing success:
https://github.com/opendp/opendp/actions/runs/10156069432/job/28083949751
dev branch updated:
https://github.com/opendp/opendp/tree/dev
=> CI: update bindings in release channels

python/src/opendp/_convert.py, python/src/opendp/context.py, python/test/context/test_context.py, python/test/test_binary_search.py, python/test/test_context_usability.py, python/test/test_convert.py, python/test/test_typing.py
- Towards #943 (not sure if there are other coercions we'd also like to see?)
- Fix #1468
Not super confident about this approach, but `check_similar_scalar` really seems to be the center of things: This gets called from many different points, so doing it outside this function seemed like a piecemeal solution.
This does fix `test_int_data_laplace_param` and I've added a lower level conversion test, but there is a change in behavior in binary search, but maybe that's ok?
Draft for now, but feedback welcome.
=> cast int to float if needed in `py_to_c`

python/src/opendp/_lib.py
Proposal. Would help debug cases like 
- #1758 
- #1885
Hopefully we don't hit this error again, but if we did, we could ask the user to list what was in that directory. It's also possible that someday there will be a problem in the logic to determine the lib_dir, and this would help us debug that.
=> report dir name if binary not found

.github/workflows/docs.yml
Closes #1893
Since no ref is stated in the checkout when building R docs, it defaults to main. However, the ideal behavior is for the docs site to show stable. 
Separately, the r-docs build began to fail because it was pointed at main, where we don't check in generated code.
=> ci: fix r-docs build

python/test/test_polars.py, rust/Cargo.toml
Closes #1882
Used to make the following script for a community meeting talk possible:
```python
import numpy as np
import polars as pl
import opendp.prelude as dp
dp.enable_features("contrib")
def synthesize_from_data(data, p_unit, p_loss, bounds, n_bins, target_size):
edges = [np.linspace(*c_bounds, num=n_bins + 1) for c_bounds in bounds.values()]
exprs = [pl.col(c).cut(c_edges).to_physical() for c, c_edges in zip(bounds, edges)]
release = (
dp.Context.compositor(
data=data.with_columns(exprs),
privacy_unit=p_unit,
privacy_loss=p_loss,
split_evenly_over=1,
)
.query()
.group_by(bounds.keys())
.agg(pl.len().dp.noise())
.release()
.collect()
)
hist = np.zeros((n_bins,) * len(bounds), dtype=int)
inds = release[[*bounds.keys()]].to_numpy()
mask = np.all((0 < inds) & (inds <= n_bins), axis=1) …
```
=> Polars: enable cutqcut

docs/source/index.rst, docs/source/theory/resources.rst
- Fix #1892
Alternatively, we could have a more thorough rewrite, perhaps only including the link to the resources page on the home page?
=> Add link to the new Learning Resources list, and to Hands-On Differential Privacy

CODE_OF_CONDUCT.md
- Fix #542  (sorry for typo in branch name)
- Replaces #1641: That should be closed.
We already have a code of conduct: Copy it over. If we actually want different text in the two locations (perhaps a summary on the site here and the full text here) that's not impossible, but there should be a link from the the summary to the full text to avoid confusion.
=> Copy existing code-of-conduct

python/src/opendp/mod.py, python/test/test_typing.py
- Fix #1930
Optimized python now fails where it should:
```
$ python -O
Python 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import opendp.prelude as dp
>>> space = (dp.atom_domain(T=float), dp.absolute_distance(T=float))
>>> laplace_mechanism = space >> dp.m.then_laplace(scale=1.)
Traceback (most recent call last):
...
opendp.mod.OpenDPException:
Attempted to use function that requires "contrib", but not enabled. See https://github.com/opendp/opendp/discussions/304, then call enable_features("contrib")
```
=> Fix `assert_feature` check

rust/src/measurements/make_private_expr/expr_noise/mod.rs, rust/src/measurements/make_private_expr/expr_noise/test.rs, rust/src/measurements/make_private_expr/expr_report_noisy_max/mod.rs, rust/src/measurements/make_private_expr/mod.rs, rust/src/measurements/make_private_expr/test.rs
Closes #1941
This makes it possible to run the Docs notebook at the tip of the stack.
=> Polars: auto-calibrate noise scale in bounded-DP

python/requirements-dev.in, python/requirements-dev.txt
Not urgent: Just keeping things up-to-date. I can't remember if we had a compelling reason to soft pin these, so just taking that off.
=> upgrade python dev dependencies

docs/source/_templates/old-version-warning.html, docs/source/_templates/versioning.html, docs/source/conf.py
- Fix #946
- Fix #1712 (we talked, and decided that it is good to keep this sidebar, once it's sorted.)
The template path suggested by sphinx-multiversion wasn't being read, perhaps because the pydata theme uses a different set of templates.
In the pydata theme, there didn't seem to be a template that is included above the article text, but in the same div; That said, the end result wasn't my initial goal, but I think it looks fine.
Sphinx-multiversion failed to set `latest_version` in the context. Seems easy enough to set by hand, even if that's not ideal.
The same warning is used on the nightly docs: I think that's ok. If we want to add more conditions, I should find a way to skip some versions so I can experiment more quickly.
`announcement` is verbatim text, rather than a template …
=> Add warning on docs for older versions

python/test/test_context_usability.py
- Towards #1977
(For fix, leaning towards failing early if the key is not a tuple.)
=> Add an `xfail` test of mistakenly using a string for a margin key.

docs/source/_templates/old-version-warning.html, rust/src/measurements/code/make_randomized_response_bitvec.rst
- Fix #1989
- Not reproducing locally: May not be pulling in the same version of numpy because of #1990, but that's a guess.
- Also incorporate a fix for a [docs-links bug](https://github.com/opendp/opendp/actions/runs/10598415088/job/29371920703#step:3:5). The new not-the-latest-version warning intersects with a new CI check for references to doc.opendp.org.
(Draft until I confirm that this does fix CI.)
=> Fix bitvec doctest

python/test/test_binary_search.py, rust/src/accuracy/mod.rs, rust/src/combinators/amplify/mod.rs, rust/src/combinators/sequential_compositor/interactive/mod.rs, rust/src/core/mod.rs, rust/src/data/ffi/mod.rs, rust/src/domains/mod.rs, rust/src/domains/polars/series/mod.rs, rust/src/ffi/mod.rs, rust/src/interactive/mod.rs, rust/src/measurements/alp/ffi.rs, rust/src/measurements/alp/mod.rs, rust/src/measurements/gaussian/float/mod.rs, rust/src/measurements/gaussian/integer/mod.rs, rust/src/measurements/laplace/integer/mod.rs, rust/src/measurements/make_private_expr/expr_noise/mod.rs, rust/src/measurements/make_private_expr/expr_report_noisy_max/mod.rs, rust/src/measures/ffi.rs, rust/src/metrics/ffi.rs, rust/src/polars/mod.rs, rust/src/traits/mod.rs, rust/src/traits/samplers/discretize/mod.rs, rust/src/traits/samplers/uniform/mod.rs, rust/src/transformations/covariance/mod.rs, rust/src/transformations/impute/ffi.rs, rust/src/transformations/make_stable_expr/expr_clip/mod.rs, rust/src/transformations/make_stable_expr/expr_discrete_quantile_score/mod.rs, rust/src/transformations/manipulation/ffi.rs, rust/src/transformations/variance/mod.rs
Towards #1422. Doesn't resolve, but provides more info in many cases. In particular, the error message for TypedMeasure and TypedMetric would have been useful during the hackathon.
=> make rust error messages more explicit

docs/source/conf.py
- Fix #1934
- Replace #1940: This is a much better solution.
Confirmed locally that this works.
=> Exclude code snips from indexing

rust/src/measurements/alp/mod.rs, rust/src/traits/cast/mod.rs, rust/src/traits/cast/test.rs
Fixes #1997
I'd consider this more of a patch than a fix. At some point when Dashu is updated, one of our tests will start to fail, and we can try to remove the patch.
https://github.com/cmpute/dashu/issues/53
=> Fix: controlled rounding for sub-sub-normals

.github/workflows/latex.yml
Close #2042
This fix is demonstrated to work because the child PR's CI runs properly.
=> don't try to latex-build deletion diffs

docs/requirements_notebooks.txt, python/setup.cfg
Close #2055
Randomgen 2.x exists now: https://pypi.org/project/randomgen/2.0.1/
requirements-dev.txt already has Numpy-2.0
=> Un-pin numpy dependency

python/src/opendp/extras/polars/__init__.py
- Fix #2025
Draft for now:
- Is this the right place for this information? I think at one time there was an idea of adding a page in the tabular data section, but this seems more like reference material.
- Is a fourth column with doctests useful? Maybe they are useful, but cramming them in a table is a mistake.
- How should we explain where these can be used? They can't be used right after the `dp`, but they will work if `noise` or another method intervenes.
- Does it make sense to do the same thing for `LazyFrame` methods?
=> Document supported polars methods

.github/workflows/build.yml, python/src/opendp/_lib.py, rust/Cargo.toml
Close #2016
* Free unused disk space so that builds don't run out of disk space when making a release
* Relax criteria for a suitable library binary, given that cibuildwheel emits tagged binaries
* Pin the version of the OpenSSL dependency to avoid build failure on linux distributions
Successful build shown here (save for dropping old nightly pypi versions):
https://github.com/opendp/opendp/actions/runs/11239240060
=> fix nightly build

python/src/opendp/_convert.py, python/test/test_usability.py
- Towards #1736
I'd be curious to understand what the expected behavior is.
Right now, the error comes from a `ctypes.cast`, where instead of getting a pointer, it gets a dict. Extracting the pointer from that dict...
```diff
def _wrap_in_slice(ptr, len_: int) -> FfiSlicePtr:
+    if isinstance(ptr, dict):
+        ptr = ptr['value']
return FfiSlicePtr(FfiSlice(ctypes.cast(ptr, ctypes.c_void_p), len_))
```
Gives us a different error:
```
E       opendp.mod.OpenDPException:
E         FFI("Error when deserializing LazyFrame. This may be because you're using features from Polars that are not currently supported. Semantic(None, "invalid type: integer `12`, expected enum")")
```
but all the other tests are still passing.
=> Add test for data loader error

docs/source/getting-started/tabular-data/index.rst, python/src/opendp/extras/numpy/__init__.py, python/src/opendp/extras/polars/__init__.py, python/src/opendp/extras/sklearn/__init__.py, python/src/opendp/extras/sklearn/decomposition/__init__.py
Just updated the documentation and some instances on comments that were referring to pip install opendp[XXX] without quotes.
These instances were found by just using grep
`grep -Ril "'opendp\[" ./`
Closes #2136
=> Updating quotes on pip install 'opendp[polars]' and others

.github/workflows/README.md, docs/Makefile, docs/robots.txt
- Towards #2145 
I'd suggest keeping the issue open until we've manually confirmed that the build has put the robots.txt in the right place at the top level.
=> Block older versions of docs

.github/workflows/smoke-test.yml, python/src/opendp/_convert.py, python/src/opendp/_lib.py, python/src/opendp/context.py, python/test/context/test_context.py, python/test/test_comb.py, python/test/test_core.py, python/test/test_meas.py, rust/opendp_tooling/src/codegen/python_typemap.json, rust/src/core/ffi.rs, rust/src/data/ffi/mod.rs, rust/src/domains/ffi.rs, rust/src/ffi/any.rs, rust/src/measurements/make_user_measurement/mod.rs, rust/src/measures/ffi.rs, rust/src/transformations/make_user_transformation/mod.rs
Closes #2149
The following changes were made in the process of fixing coverage:
Drive-by: FFI for creating RDP privacy curves from Python.
Drive-by: Allow partial chain to be the first element of the query.
Two commits, the first shows that CI fails if coverage is not complete, and the second expands coverage.
=> fix coverage check in CI, RDP function FFI

python/src/opendp/extras/polars/__init__.py, rust/src/domains/polars/expr/mod.rs, rust/src/domains/polars/frame/mod.rs, rust/src/domains/polars/frame/test.rs, rust/src/domains/polars/series/mod.rs, rust/src/measurements/make_private_expr/expr_noise/mod.rs, rust/src/measurements/make_private_lazyframe/group_by/mod.rs, rust/src/measurements/make_private_lazyframe/select/mod.rs, rust/src/transformations/make_stable_expr/expr_alias/mod.rs, rust/src/transformations/make_stable_expr/expr_binary/test.rs, rust/src/transformations/make_stable_expr/expr_boolean_function/mod.rs, rust/src/transformations/make_stable_expr/expr_cast/mod.rs, rust/src/transformations/make_stable_expr/expr_clip/mod.rs, rust/src/transformations/make_stable_expr/expr_clip/test.rs, rust/src/transformations/make_stable_expr/expr_col/mod.rs, rust/src/transformations/make_stable_expr/expr_count/mod.rs, rust/src/transformations/make_stable_expr/expr_cut/mod.rs, rust/src/transformations/make_stable_expr/expr_cut/test.rs, rust/src/transformations/make_stable_expr/expr_discrete_quantile_score/mod.rs, rust/src/transformations/make_stable_expr/expr_fill_nan/mod.rs, rust/src/transformations/make_stable_expr/expr_fill_null/mod.rs, rust/src/transformations/make_stable_expr/expr_sum/mod.rs, rust/src/transformations/make_stable_expr/expr_to_physical/mod.rs, rust/src/transformations/make_stable_expr/expr_to_physical/test.rs, rust/src/transformations/make_stable_expr/namespace_str/expr_strptime/mod.rs, rust/src/transformations/make_stable_expr/namespace_str/expr_strptime/test.rs, rust/src/transformations/make_stable_lazyframe/filter/mod.rs, rust/src/transformations/make_stable_lazyframe/h_stack/mod.rs, rust/src/transformations/make_stable_lazyframe/h_stack/test.rs, rust/src/transformations/make_stable_lazyframe/source/mod.rs
SeriesDomain had a drawback where you could update the element domain and forget to update the dtype, or vice-versa.
The refactored code retrieves the dtype from the element domain, and eliminates the dtype descriptor. This also eliminates the use of the Polars Field struct, shortening attribute access. I also added some useful helpers for setting the dtype or element domain that better reuses existing code.
The code also fixes a bug in the implementation of PartialEq for SeriesDomain-- two series domains that differ in their nullity bit would still be considered equal. This doesn't result in any potential exploits though, since our idiom is to set the input space to the previous domain's output space.
=> Polars: simplify SeriesDomain

docs/404.html
=> Link in paper is still 404, but the redirect after 5 seconds will now work

README.md, docs/README.md, docs/source/conf.py
- It looks like sphinx-multiversion was formally adopted, but all the PR and issue numbers still work. (Though the issue we reference is still open, so it probably makes sense to keep using the fork.)
- Fix the other link to go where the redirect points.
=> Fix two links

python/src/opendp/_convert.py, python/src/opendp/_lib.py, python/src/opendp/context.py, python/src/opendp/extras/sklearn/_make_eigendecomposition/__init__.py, python/src/opendp/extras/sklearn/_make_eigenvector/__init__.py, python/src/opendp/extras/sklearn/decomposition/__init__.py, python/src/opendp/typing.py
This isn't a high priority, and this isn't a global replacement, but it does tweak the signatures on many public methods. The advantage is that users could supply values that aren't exactly `list`s but are good enough, and with this change they should get fewer spurious typing errors.
- Towards #2164
=> list -> Sequence

python/test/test_ast.py
- Fix #1395
After looking for a library that would handle this, and coming back empty-handed, decided just to wrap my own, and it didn't turn out to be too complicated.
Can imagine expanding this to check that we do have the parameters in the docstring, and that we have some description for each parameter, and maybe check for return and typing info.
Going to branch from here and strengthen the tests, and start filling in some gaps in the docs.
=> docs: Check for docstrings that are out of sync

docs/source/_templates/questions-feedback.html, docs/source/conf.py
- Fix #2127. Surveyed other options, but this seems good enough. 
(If it's not good enough, then that's also good to know! I don't have any hard requirements right now to constrain the search.)
If you're working on this branch note that the iframe is a 403 if you're just loading it from `file:///`: It needs to be served by http.
Looks like this:
I've changed the font and text color to match our site, but it's still obviously a google form.
Questions to consider:
- Privacy wise, are we ok with a google form? One alternative would be to write out the html for the iframe only after the user clicks... but I think that would be a bit for work for not much gain.
- Are these questions the questions we want to ask?
- Whose responsibility is it to look at the responses?
=> docs: Feedback links

python/src/opendp/extras/sklearn/decomposition/__init__.py
- Fix #2217
Instead of making the base class dynamic (which causes trouble for Sphinx), make it just a regular class, but update the class hierarchy if the optional install is installed.
The core is getting rid of 
```python
_decomposition = import_optional_dependency('sklearn.decomposition', False)
if _decomposition is not None:
class _SKLPCA(_decomposition.PCA): # type: ignore[name-defined]
...
else: # pragma: no cover
class _SKLPCA(object): # type: ignore[no-redef]
...
```
and replacing it with
```
_decomposition = import_optional_dependency('sklearn.decomposition', False)
if _decomposition is not None:
PCA = type('PCA', (_decomposition.PCA,), dict(PCA.__dict__))  # type: ignore[assignment,misc]
```
Since it's now documented by Sphinx, fill in docstring a little: could still use more …
=> docs: fix PCA API docs

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/new-contribution.md, README.md, SECURITY.md, docs/README.md, docs/source/_templates/questions-feedback.html, docs/source/contributing/contact.rst, docs/source/contributing/getting-involved.rst
We have several places where we list communication channels:
- new issue page in github
- readme
- contact page in docs
- questions-feedback (new!)
This makes them all consistent, and drops a couple channels:
- twitter
- github discussions
I think there are enough other options and we'll benefit from being more focussed, but the more important thing here is consistency: Talk about this at a Monday meeting?
It adds office hours (but only on the readme: soft launch).
- Fix #2057 
- Fix #2226 (won't worry about prefilling subject lines)
=> docs: Consistent lists of communication channels

docs/source/getting-started/tabular-data/essential-statistics.ipynb, docs/source/getting-started/tabular-data/index.rst, docs/source/index.rst
https://github.com/opendp/opendp/actions/runs/12848639062/job/35826297642
Two are actually fixed, but just removed the Spectus link, since there's no longer anything about this library on that site.
=> Fix reported broken links

.github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/publish.yml
- fix #2277
Wait for 24.02 until after the patch release, just to reduce the number of variables if something does go wrong?
=> update ubuntu to 22.04

python/src/opendp/context.py, python/src/opendp/extras/polars/__init__.py, python/src/opendp/mod.py, python/src/opendp/typing.py, python/test/test_ast.py, rust/opendp_tooling/src/bootstrap/docstring.rs, rust/src/accuracy/code/summarize_polars_measurement.rst, rust/src/data/ffi/mod.rs, rust/src/data/ffi/polars.rs, rust/src/domains/ffi.rs, rust/src/measurements/code/make_randomized_response_bitvec.rst, rust/src/measurements/randomized_response_bitvec/mod.rs, rust/src/measures/ffi.rs, rust/src/metrics/ffi.rs, rust/src/polars/mod.rs
Left is local docs build; Right is nightly
- If we require all the directives to be in a contiguous block, `Example` comes in the right place.
- Also require doctests to be contiguous, so they don't get split into little boxes.
- Fix #1396
- The math looks better, and the `Raises` is formatted correctly.
- The formatting of the rust link is also fixed with a later commit, after this screenshot was taken.
- Fix #1967
- Not filed separately, but this is last bullet point, so fix #2188 
Also:
- No issue filed, but fix the rendering of numbered lists and bullet lists.
- Fix formatting of links to rust docs...
- RST does not support nested inline markup
- There is a [package](https://silverrainz.me/blog/sphinxnotes-comboroles.html) that may add support for this, but I don't think it's worth …
=> docs: Add AST checks on the formatting of the docstring

python/src/opendp/context.py, python/src/opendp/extras/_utilities.py, python/src/opendp/extras/polars/__init__.py, python/src/opendp/extras/sklearn/decomposition/__init__.py, python/src/opendp/mod.py, python/src/opendp/typing.py, python/test/test_ast.py, rust/opendp_tooling/src/codegen/python.rs, rust/src/measures/ffi.rs
- Prompted by #2259
Make sure we document all of our public classes. The changes here do that a few different ways.
- Fill in new documentation
- Move docstrings up from `__init__` that weren't being rendered. (This is the default, but like everything else [it could be configured](https://stackoverflow.com/questions/5599254/how-to-use-sphinxs-autodoc-to-document-a-classs-init-self-method).)
- Make classes that don't seem intended for end user use private. (Maybe more of this?)
The `__init__` docs weren't being checked, but I could imagine checking that the new class docstrings are consistent with constructor parameters.
=> docs: Check for doctrings on classes

.github/workflows/smoke-test.yml, rust/src/accuracy/tail_bounds/mod.rs
If this isn't something we would expect to pass, it would be good for me to understand that, too.
- Fix #2272
=> Make sure default `cargo test` also passes

python/src/opendp/_convert.py, python/src/opendp/mod.py, python/src/opendp/typing.py, python/test/test_comb.py, rust/opendp_tooling/src/bootstrap/arguments.rs, rust/opendp_tooling/src/bootstrap/mod.rs, rust/opendp_tooling/src/codegen/python.rs, rust/opendp_tooling/src/codegen/python_typemap.json, rust/opendp_tooling/src/codegen/r/c.rs, rust/opendp_tooling/src/codegen/test.rs, rust/opendp_tooling/src/lib.rs, rust/src/combinators/amplify/ffi.rs, rust/src/combinators/chain/ffi.rs, rust/src/combinators/fix_delta/ffi.rs, rust/src/combinators/measure_cast/zCDP_to_approxDP/ffi.rs, rust/src/combinators/select_private_candidate/mod.rs, rust/src/combinators/sequential_compositor/noninteractive/ffi.rs, rust/src/core/ffi.rs, rust/src/domains/ffi.rs, rust/src/ffi/any.rs, rust/src/ffi/util.rs, rust/src/internal/mod.rs, rust/src/measurements/make_user_measurement/mod.rs, rust/src/measures/ffi.rs, rust/src/transformations/make_user_transformation/mod.rs
Fix #2235
The plugin APIs embed Python objects inside opaque Rust structs (transformation, measurement, queryable, function, domain, privacy profile, etc).
Imagine a user defines a custom function and uses the plugin API to embed it into a Rust struct.
When execution continues, the Rust struct holds a pointer to memory allocated in Python. 
Unfortunately, Python doesn't know the memory is still being referenced by Rust, 
and the Python refcount to that object naturally drops to zero.
The Python interpreter then frees the object upon the next garbage collection, leading to a use-after-free memory corruption when the Rust struct is used.
Previously, the generated code would add a reference to any Python objects embedded in the Rust struct, to the corresponding opaque struct on the Python …
=> fix: replace _dependencies with lifelines

python/conftest.py, python/test/test_tests.py
- Fix #2245
- Prereq to #2205
This might be needlessly complicated, but the idea is that instead of simply ignoring the result altogether, we can loosen it, so that if the RST has a number preceded by tilde, any number will work, but the rest of the output still needs to match.
FYI: Pytest has a related doctest extension: [NUMBER](https://docs.pytest.org/en/7.1.x/how-to/doctest.html?highlight=doctest#using-doctest-options).
> when enabled, floating-point numbers only need to match as far as the precision you have written in the expected doctest output
The [source code](https://github.com/pytest-dev/pytest/blob/2f369848ea0ead42182efc77000a5ecef629a0ba/src/_pytest/doctest.py#L654-L676) is interesting.
=> testing: Fuzzy doctests

python/src/opendp/mod.py, python/test/extras/test_ext_domains.py, python/test/test_core.py, python/test/test_serialization.py
- fix #1007
- Fix #2262
Python is less rigorous than Rust, and I think most users are just going to expect `member` to return a bool. But we do have a side channel to pass more information, if the user wants more information: warnings.
(This is motivated by wanting to write stronger tests of serialization, but its not strictly necessary for that: I could just have `with pytest.warns()` blocks.)
=> feat: `member` is true or false, with a warning; Expand serialization tests

.github/workflows/smoke-test.yml
- Fix #2301 by using `ubunutu-latest` for all but `rust-test`.
- Fix #2276
- Filed a follow-up issue: #2305
=> chore: Update Ubuntu in CI

R/opendp/src/convert_elements.c, docs/source/api/user-guide/combinators/index.rst, python/test/test_comb.py, rust/src/combinators/measure_cast/fixed_approxDP_to_approxDP/ffi.rs, rust/src/combinators/measure_cast/fixed_approxDP_to_approxDP/mod.rs, rust/src/combinators/measure_cast/fixed_approxDP_to_approxDP/test.rs, rust/src/combinators/measure_cast/mod.rs
Closes #2021 
Translate mechanisms with an (ε, δ) guarantee into a trivial δ(ε) guarantee (with a piecewise constant profile). This will make it possible to view relative risk and α(β) curves on any pure-DP or fixed approx-DP mechanism.
=> feat: add `make_fixed_approxDP_to_approxDP`

.github/workflows/build.yml, .github/workflows/smoke-test.yml, rust/Cargo.toml
Related to #2305
Ubuntu 24.04 updated glibc beyond 0.39, where glibc changed header functions to add `cstd23` aliases for various functions. Our GitHub actions speeds up the build by reusing/caching rlib files from parent actions, which use Ubuntu 24.04. Therefore the openssl-sys rlib from the cache contains references to glibc `cstd23` functions that are only valid on Ubuntu 24.04, which don't yet exist in the glibc of Ubuntu 22.xx.
This PR standardizes CI to ubuntu-22.04, and updates pip to fix a packaging.licenses docs CI failure.
=> fix: openssl compilation in smoke-test

python/src/opendp/context.py, python/test/test_polars.py, python/test/test_usability.py
- Fix #2297
I'd have a slight preference that there be one right way to use the library, just so the users aren't left wondering if the dict and list somehow work differently. Feel free to close if this seems too fussy.
=> Deprecate margins dict

python/test/test_ast.py
- Fix #2296
I think this has nudged us in a good direction, but in the long run I don't think we need to maintain this tooling. Either docsig or pydoclint might be a good replacement.
=> Docs: Add a note about tools to consider for param consistency checks

.github/workflows/weekly-doc-check.yml
- Fix #2301
The saga continues:
- We first tried upgrading ubuntu to latest everywhere
- That didn't work for Rust for some reason, so we kept that action on an older ubuntu version
- But then there was a mismatch in the opendp binary that later actions need
- So we ended up pinning all the actions to an older ubuntu, and for smoke-test added an upgrade for pip
- _but we forgot the same upgrade for the link checker!_
- so add that in this PR.
=> feat: Add pip upgrade to link checker

docs/source/api/user-guide/plugins/context-api-plugins.rst, docs/source/api/user-guide/plugins/index.rst, docs/source/api/user-guide/plugins/measurement.rst, python/src/opendp/context.py, python/src/opendp/extras/_utilities.py, python/src/opendp/extras/numpy/_make_np_clamp/__init__.py, python/src/opendp/extras/sklearn/_make_eigendecomposition/__init__.py, python/src/opendp/extras/sklearn/decomposition/__init__.py, python/test/context/test_context.py
#1382 was not resolved
closes #2338 
This PR also stops registering constructors in the generated modules, opting instead to register them in the context API.
=> feat: constructor registration in Context API

python/src/opendp/extras/sklearn/decomposition/__init__.py, python/test/extras/test_pca.py
Closes #2363
Sklearn is pinned in CI, but not in the package. A newer version of sklearn introduced a regression for us that prevents us from using the type trick to inherit from a class in an optional dependency.
=> fix: exception in PCA constructor

python/test/test_usability.py, rust/src/transformations/make_stable_expr/expr_sum/mod.rs
- Fix #2314 
@Shoeboxam , I realize looking at this that it doesn't test the case where `by` isn't empty. I thought the grouping might trigger that. Ideas?
=> feat: Add more info for the user in `max_partition_length` error message 

.github/workflows/weekly-doc-check.yml, README.md, docs/linkchecker-external.cfg, docs/source/getting-started/tabular-data/essential-statistics.ipynb, docs/source/theory/attacks/membership.ipynb, docs/source/theory/resources.rst
- Fix #2401
Looks like `privacytools.seas.harvard.edu` was rearranged: Annoying, but I don't think it makes sense to bother asking for the restoration of the old links.
=> Fix link check

docs/404.html
- Fix #2396
I expect that another PR
- #2403
will re-establish the `getting-started/statistical-modeling/regression.html` path, but it would be good to point users to the new location until that is merged. (That PR will probably remove this redirect.)
=> docs: JS redirection for regression

docs/source/getting-started/index.rst
- Fix #2409
I had forgotten that our examples page had moved. Propose linking directly to the live demo, or maybe that's too aggressive? But linking to the project page just gives them too much to read and sort through.
=> docs: add dp-wizard link

rust/src/combinators/chain/mod.rs, rust/src/combinators/sequential_composition/adaptive/ffi.rs, rust/src/combinators/sequential_composition/adaptive/mod.rs, rust/src/combinators/sequential_composition/adaptive/test.rs, rust/src/combinators/sequential_composition/ffi.rs, rust/src/combinators/sequential_composition/mod.rs, rust/src/combinators/sequential_composition/non_adaptive/mod.rs, rust/src/combinators/sequential_composition/non_adaptive/test.rs, rust/src/core/mod.rs, rust/src/core/test.rs, rust/src/data/ffi/mod.rs, rust/src/ffi/any.rs, rust/src/interactive/mod.rs, rust/src/measurements/make_private_expr/expr_postprocess/mod.rs, rust/src/measurements/make_private_expr/mod.rs, rust/src/measurements/make_private_lazyframe/group_by/mod.rs, rust/src/measurements/make_private_lazyframe/mod.rs, rust/src/measurements/make_private_lazyframe/postprocess/mod.rs, rust/src/measurements/make_private_lazyframe/select/mod.rs, rust/src/measures/ffi.rs, rust/src/metrics/ffi.rs
Closes #2421
This PR also drops the Send and Sync bounds for threading. This was primarily added for compatibility with Polars, but was ultimately not necessary. While threading is nice, the extra pain from the bounds compounds with odometers, and we don't seem to need it.
=> fix: interactive postprocessing under sequentiality constraint

docs/source/api/user-guide/plugins/theil-sen-regression.ipynb
- Fix #2484
I think what happened was that notebooks are converted to rst before rendering to html, but rst syntax does not support nested tags. To fix this, we can just make the link plain text, and I've confirmed locally that it renders nicely.
=> docs: fix linear regression link

python/src/opendp/context.py, python/src/opendp/extras/examples/__init__.py, python/src/opendp/extras/mbi/__init__.py, python/src/opendp/extras/numpy/__init__.py, python/src/opendp/extras/numpy/canonical.py, python/src/opendp/extras/polars/__init__.py, python/src/opendp/extras/polars/contingency_table.py, python/src/opendp/extras/sklearn/__init__.py, python/src/opendp/extras/sklearn/decomposition/__init__.py, python/src/opendp/extras/sklearn/linear_model/__init__.py, python/src/opendp/typing.py, python/test/test_docs.py
- Fix #2486
This got a little more complicated than I would have liked, but it should make sure the text gets added to any new modules.
=> docs: Add missing docstring boilerplate in extras

docs/source/getting-started/statistical-modeling/index.rst, docs/source/getting-started/statistical-modeling/linear-regression.rst
- Fix #2482
- Provide more explanation of the available tools: Mention sklearn influence, and explain what synthetic data is good for... and not so good for.
- Add a placeholder page for linear regression. Usually I want the getting started to be self-contained, but we already have examples of linear regression in two places, and I don't want to add a third, so pointers will do. Having a statistics section and _not_ mentioning linear regression feels like a gap.
=> Clean up stats ToC in getting-started

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/docs.md, .github/ISSUE_TEMPLATE/new-contribution.md, .github/ISSUE_TEMPLATE/new-mechanism.md, .github/ISSUE_TEMPLATE/reminder.md, .github/ISSUE_TEMPLATE/usability.md
- Fix #2516
@Shoeboxam , I think it's much easier to capture tags and other metadata when the issue is first filed. Do you think there should be any other categories?
I was thinking about assigning to myself by default for triage, but I'm not sure about that now.
=> docs: update issue templates
